-- [alcohol]
return {
    ["7and7"] = { label = "7and7" },
    ["amaretto"] = { label = "Amaretto" },
    ["amarone"] = { label = "Amarone" },
    ["beerglass"] = { label = "Beerglass" },
    ["beerglass2"] = { label = "Beerglass2" },
    ["beerglass3"] = { label = "Beerglass3" },
    ["bellini"] = { label = "Bellini" },
    ["blackrussian"] = { label = "Blackrussian" },
    ["bloodymary"] = { label = "Bloodymary" },
    ["bluekamikaze"] = { label = "Bluekamikaze" },
    ["champagne"] = { label = "Champagne" },
    ["cosmopolitan"] = { label = "Cosmopolitan" },
    ["curaco"] = { label = "Curaco" },
    ["daquirimint"] = { label = "Daquirimint" },
    ["daquiristraw"] = { label = "Daquiristraw" },
    ["drimartini"] = { label = "Drimartini" },
    ["gin"] = { label = "Gin" },
    ["gin2"] = { label = "Gin2" },
    ["gin_and_tonic"] = { label = "Gin et Tonic" },
    ["irishcream"] = { label = "Irishcream" },
    ["kamikaze"] = { label = "Kamikaze" },
    ["longisland"] = { label = "Longisland" },
    ["maitai"] = { label = "Maitai" },
    ["manhattin"] = { label = "Manhattin" },
    ["margarita"] = { label = "Margarita" },
    ["margaritacuraco"] = { label = "Margaritacuraco" },
    ["margaritastraw"] = { label = "Margaritastraw" },
    ["midori"] = { label = "Midori" },
    ["mimosa"] = { label = "Mimosa" },
    ["mojito"] = { label = "Mojito" },
    ["negroni"] = { label = "Negroni" },
    ["oldfashioned"] = { label = "Oldfashioned" },
    ["pinacolada"] = { label = "Pinacolada" },
    ["rosso"] = { label = "Rosso" },
    ["rum"] = { label = "Rum" },
    ["rum_and_cola"] = { label = "Rum et Cola" },
    ["sangria"] = { label = "Sangria" },
    ["schnapps"] = { label = "Schnapps" },
    ["scotch"] = { label = "Scotch" },
    ["screwdriver"] = { label = "Screwdriver" },
    ["shirleytemple"] = { label = "Shirleytemple" },
    ["shooter_applepie"] = { label = "Shooter Tarte aux pommes" },
    ["shooter_b52"] = { label = "Shooter B52" },
    ["shooter_ccookie"] = { label = "Shooter Ccookie" },
    ["shooter_coffee_liqure"] = { label = "Shooter Coffee Liqure" },
    ["shooter_electricjello_blue"] = { label = "Shooter Electricjello Blue" },
    ["shooter_electricjello_lime"] = { label = "Shooter Electricjello Lime" },
    ["shooter_electricjello_red"] = { label = "Shooter Electricjello Rouge" },
    ["shooter_irishflag"] = { label = "Shooter Irishflag" },
    ["shooter_sbullet"] = { label = "Shooter Sbullet" },
    ["shooter_tequila"] = { label = "Shooter Tequila" },
    ["shooter_voodoo"] = { label = "Shooter Voodoo" },
    ["shooter_whiskey"] = { label = "Shooter Whiskey" },
    ["singaporesling"] = { label = "Singaporesling" },
    ["sour_amaretto"] = { label = "Sour Amaretto" },
    ["sour_whiskey"] = { label = "Sour Whiskey" },
    ["tequila"] = { label = "Tequila" },
    ["tomcollins"] = { label = "Tomcollins" },
    ["triplesec"] = { label = "Triplesec" },
    ["vodka"] = { label = "Vodka" },
    ["whiskey"] = { label = "Whiskey" },
    ["whiskey_rocks"] = { label = "Whiskey Rocks" },
    ["wine_barbera"] = { label = "Vin Barbera" },
    ["wine_chardoney"] = { label = "Vin Chardoney" },
    ["wine_chardonnay"] = { label = "Vin Chardonnay" },
    ["wine_dolcetto"] = { label = "Vin Dolcetto" },
    ["wine_merlot"] = { label = "Vin Merlot" },
    ["wine_prosecco"] = { label = "Vin Prosecco" },
    ["wine_red"] = { label = "Vin Rouge" },
    ["wine_rose"] = { label = "Vin Rosé" },
    ["wine_white"] = { label = "Vin Blanc" },
    ["woowoo"] = { label = "Woowoo" },
}
