-- [crafting]
return {
    ["aluminum"] = { label = "Aluminum" },
    ["bin_blue"] = { label = "Bin Blue" },
    ["bin_red"] = { label = "Bin Rouge" },
    ["bird_feather"] = { label = "Bird Feather" },
    ["bottle"] = { label = "Bottle" },
    ["bucket"] = { label = "Bucket" },
    ["butcherpaper"] = { label = "Butcherpaper" },
    ["can"] = { label = "Canette" },
    ["circuit_board"] = { label = "Circuit Board" },
    ["cloth"] = { label = "Cloth" },
    ["copper"] = { label = "Copper" },
    ["copper_wires"] = { label = "Copper Wires" },
    ["glass"] = { label = "Glass" },
    ["hammer"] = { label = "Hammer" },
    ["lithium_battery"] = { label = "Lithium Pile" },
    ["metalscrap"] = { label = "Metalscrap" },
    ["plastic"] = { label = "Plastic" },
    ["rolling_paper"] = { label = "Rolling Paper" },
    ["rolling_paper2"] = { label = "Rolling Paper2" },
    ["rope"] = { label = "Rope" },
    ["rubber"] = { label = "Rubber" },
    ["snspistol_part_1"] = { label = "Snspistol Part 1" },
    ["snspistol_part_2"] = { label = "Snspistol Part 2" },
    ["snspistol_part_3"] = { label = "Snspistol Part 3" },
    ["steel_plate"] = { label = "Steel Plate" },
    ["tape_duct"] = { label = "Tape Duct" },
    ["tape_electrical"] = { label = "Tape Electrical" },
    ["wood_cedar"] = { label = "Wood Cedar" },
    ["wood_maple"] = { label = "Wood Maple" },
    ["wood_oak"] = { label = "Wood Oak" },
    ["wood_pine"] = { label = "Wood Pine" },
}
