-- [crime]
return {
    ["1000bearerbond"] = { label = "1000bearerbond" },
    ["adress_book"] = { label = "Adress Book" },
    ["advancedlockpick"] = { label = "Advancedlockpick" },
    ["bag"] = { label = "Sac" },
    ["bomb"] = { label = "Bomb" },
    ["co2"] = { label = "Co2" },
    ["cryptostick"] = { label = "Cryptostick" },
    ["drill"] = { label = "Drill" },
    ["drillbit"] = { label = "Drillbit" },
    ["electronickit"] = { label = "Electronickit" },
    ["gasmask"] = { label = "Gasmask" },
    ["generator"] = { label = "Générateur" },
    ["gps_hacking_device"] = { label = "GPS Hacking Device" },
    ["hacking_device"] = { label = "Hacking Device" },
    ["hacking_device2"] = { label = "Hacking Device2" },
    ["handgun"] = { label = "Pistolet" },
    ["hardrive"] = { label = "Disque dur" },
    ["head_bag"] = { label = "Head Sac" },
    ["hlabs_chemicals"] = { label = "Hlabs Produit chimique" },
    ["hlabs_formula"] = { label = "Hlabs Formula" },
    ["hydrochloricacid"] = { label = "Hydrochloricacid" },
    ["hydrogen"] = { label = "Hydrogen" },
    ["ironoxide"] = { label = "Ironoxide" },
    ["lockpick"] = { label = "Crochetage" },
    ["markedbills"] = { label = "Markedbills" },
    ["moneybag"] = { label = "Moneybag" },
    ["multitool"] = { label = "Multitool" },
    ["plate"] = { label = "Plate" },
    ["rolex"] = { label = "Rolex" },
    ["scale"] = { label = "Scale" },
    ["screwdriverset"] = { label = "Tournevis" },
    ["stolenmicro"] = { label = "Stolenmicro" },
    ["stolenstereo"] = { label = "Stolenstereo" },
    ["stolentv"] = { label = "Stolentv" },
}
