-- [drugs]
return {
    ["1gheroin"] = { label = "1gheroin" },
    ["Coca-leaves"] = { label = "Coca Leaves" },
    ["acapulcogold_leaf"] = { label = "Acapulcogold Leaf" },
    ["acapulcogold_seed"] = { label = "Acapulcogold Graine" },
    ["acapulcogold_trimmed_bud"] = { label = "Acapulcogold Trimmed Bud" },
    ["acapulcogold_untrimmed_bud"] = { label = "Acapulcogold Untrimmed Bud" },
    ["acetone"] = { label = "Acétone" },
    ["acetonebarrel"] = { label = "Acetonebarrel" },
    ["acyclovir"] = { label = "Acyclovir" },
    ["aluminumoxide"] = { label = "Aluminumoxide" },
    ["ammonia"] = { label = "Ammoniac" },
    ["ammonium_nitrate"] = { label = "Ammonium Nitrate" },
    ["ammoniumnitrate"] = { label = "Ammoniumnitrate" },
    ["ammoniumnitratebarrel"] = { label = "Ammoniumnitratebarrel" },
    ["babypowder"] = { label = "Babypowder" },
    ["baggy_cocaine"] = { label = "Sachet Cocaïne" },
    ["baggy_empty"] = { label = "Sachet Vide" },
    ["baggy_empty2"] = { label = "Sachet Empty2" },
    ["baggy_extasy"] = { label = "Sachet Extasy" },
    ["baggy_meth"] = { label = "Sachet Méthamphétamine" },
    ["baggy_methLG"] = { label = "Sachet Methlg" },
    ["baggy_weed"] = { label = "Sachet Weed" },
    ["beaker"] = { label = "Beaker" },
    ["big_scale"] = { label = "Big Scale" },
    ["blunt"] = { label = "Blunt" },
    ["bluntwrap"] = { label = "Bluntwrap" },
    ["brick_cocaine"] = { label = "Brick Cocaïne" },
    ["brick_cocaine2"] = { label = "Brick Cocaine2" },
    ["brick_meth"] = { label = "Brick Méthamphétamine" },
    ["brick_opium"] = { label = "Brick Opium" },
    ["brick_weed"] = { label = "Brick Weed" },
    ["cannabis"] = { label = "Cannabis" },
    ["cannibis"] = { label = "Cannibis" },
    ["chemicalmixer"] = { label = "Chemicalmixer" },
    ["cocaine"] = { label = "Cocaïne" },
    ["cocaineleaf"] = { label = "Cocaineleaf" },
    ["cocaleaf"] = { label = "Cocaleaf" },
    ["codeine"] = { label = "Codeine" },
    ["cokepackage"] = { label = "Cokepackage" },
    ["colombiangold_leaf"] = { label = "Colombiangold Leaf" },
    ["colombiangold_seed"] = { label = "Colombiangold Graine" },
    ["colombiangold_trimmed_bud"] = { label = "Colombiangold Trimmed Bud" },
    ["colombiangold_untrimmed_bud"] = { label = "Colombiangold Untrimmed Bud" },
    ["crack_baggy"] = { label = "Crack Sachet" },
    ["crackmixingagent"] = { label = "Crackmixingagent" },
    ["distilledwater"] = { label = "Distilledwater" },
    ["dosidos_leaf"] = { label = "Dosidos Leaf" },
    ["dosidos_seed"] = { label = "Dosidos Graine" },
    ["dosidos_trimmed_bud"] = { label = "Dosidos Trimmed Bud" },
    ["dosidos_untrimmed_bud"] = { label = "Dosidos Untrimmed Bud" },
    ["drug_lean"] = { label = "Drug Lean" },
    ["drug_phone"] = { label = "Drug Phone" },
    ["ecgonine"] = { label = "Ecgonine" },
    ["emptychembottles"] = { label = "Emptychembottles" },
    ["formaldehyde"] = { label = "Formaldehyde" },
    ["gelpills_blue"] = { label = "Gelpills Blue" },
    ["gelpills_pink"] = { label = "Gelpills Pink" },
    ["gelpills_red"] = { label = "Gelpills Rouge" },
    ["gelpills_yellow"] = { label = "Gelpills Yellow" },
    ["greengelato_trimmed_bud"] = { label = "Greengelato Trimmed Bud" },
    ["hiqualitysoil"] = { label = "Hiqualitysoil" },
    ["hiqualnutrients"] = { label = "Hiqualnutrients" },
    ["joint"] = { label = "Joint" },
    ["joint2"] = { label = "Joint2" },
    ["lab"] = { label = "Lab" },
    ["lean"] = { label = "Lean" },
    ["lemonskunk_leaf"] = { label = "Lemonskunk Leaf" },
    ["lemonskunk_seed"] = { label = "Lemonskunk Graine" },
    ["lemonskunk_trimmed_bud"] = { label = "Lemonskunk Trimmed Bud" },
    ["lemonskunk_untrimmed_bud"] = { label = "Lemonskunk Untrimmed Bud" },
    ["liquid_sulfur"] = { label = "Liquid Soufre" },
    ["lithium"] = { label = "Lithium" },
    ["lithiumbarrel"] = { label = "Lithiumbarrel" },
    ["lowqualitysoil"] = { label = "Lowqualitysoil" },
    ["lsd"] = { label = "LSD" },
    ["lsdtab"] = { label = "Lsdtab" },
    ["magic_mushroom"] = { label = "Magique Champignon" },
    ["medqualnutrients"] = { label = "Medqualnutrients" },
    ["meth"] = { label = "Méthamphétamine" },
    ["meth_tray"] = { label = "Méthamphétamine Tray" },
    ["meth_tray2"] = { label = "Méthamphétamine Tray2" },
    ["methalmine2"] = { label = "Methalmine2" },
    ["methylamine_barrel"] = { label = "Methylamine Barrel" },
    ["muriatic_acid"] = { label = "Muriatic Acide" },
    ["murioticacid"] = { label = "Murioticacid" },
    ["murioticacidbarrel"] = { label = "Murioticacidbarrel" },
    ["northernlights_leaf"] = { label = "Northernlights Leaf" },
    ["northernlights_seed"] = { label = "Northernlights Graine" },
    ["northernlights_trimmed_bud"] = { label = "Northernlights Trimmed Bud" },
    ["northernlights_untrimmed_bud"] = { label = "Northernlights Untrimmed Bud" },
    ["ogkush_leaf"] = { label = "Ogkush Leaf" },
    ["ogkush_seed"] = { label = "Ogkush Graine" },
    ["ogkush_trimmed_bud"] = { label = "Ogkush Trimmed Bud" },
    ["ogkush_untrimmed_bud"] = { label = "Ogkush Untrimmed Bud" },
    ["peyote_button"] = { label = "Peyote Button" },
    ["peyote_seed"] = { label = "Peyote Graine" },
    ["pills_extasy"] = { label = "Pilules Extasy" },
    ["pills_fentanyl"] = { label = "Pilules Fentanyl" },
    ["plantpot"] = { label = "Plantpot" },
    ["plasticbag"] = { label = "Plasticbag" },
    ["poppy"] = { label = "Pavot" },
    ["rainbowbelts_leaf"] = { label = "Rainbowbelts Leaf" },
    ["rainbowbelts_seed"] = { label = "Rainbowbelts Graine" },
    ["rainbowbelts_trimmed_bud"] = { label = "Rainbowbelts Trimmed Bud" },
    ["rainbowbelts_untrimmed_bud"] = { label = "Rainbowbelts Untrimmed Bud" },
    ["red_sulfur"] = { label = "Rouge Soufre" },
    ["redsulfurbarrel"] = { label = "Redsulfurbarrel" },
    ["sacid"] = { label = "Sacid" },
    ["small-scale"] = { label = "Small Scale" },
    ["sodium_hydroxide"] = { label = "Sodium Hydroxide" },
    ["sodiumbicarbonate"] = { label = "Sodiumbicarbonate" },
    ["sodiumhydroxide"] = { label = "Sodiumhydroxide" },
    ["sodiumhydroxidebarrel"] = { label = "Sodiumhydroxidebarrel" },
    ["weed_butter"] = { label = "Weed Butter" },
    ["weed_gummies"] = { label = "Weed Gummies" },
    ["weed_laced"] = { label = "Weed Laced" },
    ["weed_oil"] = { label = "Weed Oil" },
    ["weed_ream"] = { label = "Weed Ream" },
    ["weedscissors"] = { label = "Weedscissors" },
}
