-- [electronics]
return {
    ["battery_9v"] = { label = "Pile 9v" },
    ["battery_aaa"] = { label = "Pile Aaa" },
    ["battery_d2"] = { label = "Pile D2" },
    ["battery_package_9v"] = { label = "Pile Paquet 9v" },
    ["battery_package_aaa"] = { label = "Pile Paquet Aaa" },
    ["battery_package_d2"] = { label = "Pile Paquet D2" },
    ["cdplayer"] = { label = "Cdplayer" },
    ["e2_cpu"] = { label = "E2 Cpu" },
    ["internals"] = { label = "Internals" },
    ["miniradio"] = { label = "Miniradio" },
    ["nikon"] = { label = "Nikon" },
    ["portablecopier"] = { label = "Portablecopier" },
    ["powerbank"] = { label = "Batterie externe" },
    ["printer_document"] = { label = "Imprimante Document" },
    ["quantum_cpu"] = { label = "Quantum Cpu" },
    ["radio"] = { label = "Radio" },
    ["radioscanner"] = { label = "Radioscanner" },
    ["server_drive"] = { label = "Serveur Clé" },
    ["simcard"] = { label = "Simcard" },
    ["standard_cpu"] = { label = "Standard Cpu" },
    ["stolencomputer"] = { label = "Stolencomputer" },
    ["tablet"] = { label = "Tablette" },
    ["usb_drive1"] = { label = "USB Drive1" },
    ["usb_drive2"] = { label = "USB Drive2" },
    ["usb_drive3"] = { label = "USB Drive3" },
    ["usb_drive4"] = { label = "USB Drive4" },
}
