-- [ems]
return {
    ["Inhailer"] = { label = "Inhailer" },
    ["Trilenol"] = { label = "Trilenol" },
    ["aed"] = { label = "Aed" },
    ["antibiotics"] = { label = "Antibiotiques" },
    ["armbrace"] = { label = "Armbrace" },
    ["armor_ems"] = { label = "Armure Ems" },
    ["aspirin"] = { label = "Aspirin" },
    ["azithromycin"] = { label = "Azithromycin" },
    ["bandage"] = { label = "Bandage" },
    ["bloodbag"] = { label = "Bloodbag" },
    ["bloodsample"] = { label = "Bloodsample" },
    ["bodybrace"] = { label = "Bodybrace" },
    ["burndressing"] = { label = "Burndressing" },
    ["coldnflubox"] = { label = "Coldnflubox" },
    ["crutch"] = { label = "Béquille" },
    ["dramamine"] = { label = "Dramamine" },
    ["ephedrine"] = { label = "Ephedrine" },
    ["epi_pen"] = { label = "Epi Pen" },
    ["firstaid"] = { label = "Trousse de secours" },
    ["glucosemeter"] = { label = "Glucosemeter" },
    ["ifaks"] = { label = "Ifaks" },
    ["laxative"] = { label = "Laxative" },
    ["legbrace"] = { label = "Legbrace" },
    ["medbag2"] = { label = "Medbag2" },
    ["medbag3"] = { label = "Medbag3" },
    ["medbag4"] = { label = "Medbag4" },
    ["medbox"] = { label = "Boîte médicale" },
    ["medbox6"] = { label = "Medbox6" },
    ["mri"] = { label = "IRM" },
    ["neckbrace"] = { label = "Neckbrace" },
    ["oxy"] = { label = "Oxy" },
    ["oxygen"] = { label = "Oxygène" },
    ["painkillers"] = { label = "Antidouleur" },
    ["peptobismol"] = { label = "Peptobismol" },
    ["pseudophederine"] = { label = "Pseudophederine" },
    ["salinebag"] = { label = "Salinebag" },
    ["surgicalkit"] = { label = "Surgicalkit" },
    ["suturekit"] = { label = "Suturekit" },
    ["syringe"] = { label = "Seringue" },
    ["syringefull"] = { label = "Syringefull" },
    ["walkstick"] = { label = "Walkstick" },
    ["walkstick2"] = { label = "Walkstick2" },
    ["xray"] = { label = "Radiographie" },
}
