-- [farming]
return {
    ["apple"] = { label = "Apple" },
    ["apple_crate"] = { label = "Apple Caisse" },
    ["barley"] = { label = "Barley" },
    ["barley_sack"] = { label = "Barley Sac" },
    ["barley_seed"] = { label = "Barley Graine" },
    ["blueberry"] = { label = "Blueberry" },
    ["blueberry_crate"] = { label = "Blueberry Caisse" },
    ["blueberry_seed"] = { label = "Blueberry Graine" },
    ["broccoli"] = { label = "Broccoli" },
    ["broccoli_crate"] = { label = "Broccoli Caisse" },
    ["broccoli_seed"] = { label = "Broccoli Graine" },
    ["cactus_seed"] = { label = "Cactus Graine" },
    ["cactusfruit"] = { label = "Fruit de cactus" },
    ["cactusfruit_crate"] = { label = "Fruit de cactus Caisse" },
    ["carrot"] = { label = "Carrot" },
    ["carrot_crate"] = { label = "Carrot Caisse" },
    ["carrot_raw"] = { label = "Carrot Cru" },
    ["carrot_seed"] = { label = "Carrot Graine" },
    ["corn"] = { label = "Corn" },
    ["corn_crate"] = { label = "Corn Caisse" },
    ["corn_raw"] = { label = "Corn Cru" },
    ["corn_seed"] = { label = "Corn Graine" },
    ["cucumber"] = { label = "Cucumber" },
    ["cucumber_crate"] = { label = "Cucumber Caisse" },
    ["cucumber_seed"] = { label = "Cucumber Graine" },
    ["egg"] = { label = "Egg" },
    ["egg_crate"] = { label = "Egg Caisse" },
    ["emptycrate"] = { label = "Emptycrate" },
    ["emptysack"] = { label = "Emptysack" },
    ["farm_fertilizer"] = { label = "Ferme Engrais" },
    ["farmguide"] = { label = "Guide agricole" },
    ["garden_pitcher"] = { label = "Jardin Arrosoir" },
    ["garden_shovel"] = { label = "Jardin Pelle" },
    ["lemon"] = { label = "Lemon" },
    ["lemon_crate"] = { label = "Lemon Caisse" },
    ["lettuce"] = { label = "Lettuce" },
    ["lettuce_crate"] = { label = "Lettuce Caisse" },
    ["lettuce_seed"] = { label = "Lettuce Graine" },
    ["lime"] = { label = "Lime" },
    ["lime_crate"] = { label = "Lime Caisse" },
    ["maize"] = { label = "Maize" },
    ["maize_sack"] = { label = "Maize Sac" },
    ["maize_seed"] = { label = "Maize Graine" },
    ["milk"] = { label = "Lait" },
    ["milk_crate"] = { label = "Lait Caisse" },
    ["milk_pail"] = { label = "Lait Seau" },
    ["milking_pail"] = { label = "Milking Seau" },
    ["mushroom"] = { label = "Champignon" },
    ["mushroom_sack"] = { label = "Champignon Sac" },
    ["mushroom_seed"] = { label = "Champignon Graine" },
    ["orange"] = { label = "Orange" },
    ["orange_crate"] = { label = "Orange Caisse" },
    ["peach"] = { label = "Peach" },
    ["peach_crate"] = { label = "Peach Caisse" },
    ["pineapple"] = { label = "Pineapple" },
    ["pineapple_crate"] = { label = "Pineapple Caisse" },
    ["pineapple_seed"] = { label = "Pineapple Graine" },
    ["potato"] = { label = "Potato" },
    ["potato_raw"] = { label = "Potato Cru" },
    ["potato_sack"] = { label = "Potato Sac" },
    ["potato_seed"] = { label = "Potato Graine" },
    ["strawberry"] = { label = "Strawberry" },
    ["strawberry_crate"] = { label = "Strawberry Caisse" },
    ["strawberry_seed"] = { label = "Strawberry Graine" },
    ["tomato"] = { label = "Tomato" },
    ["tomato_crate"] = { label = "Tomato Caisse" },
    ["tomato_seed"] = { label = "Tomato Graine" },
    ["watering_can"] = { label = "Arrosage Canette" },
    ["watering_can_full"] = { label = "Arrosage Canette Plein" },
    ["wheat"] = { label = "Wheat" },
    ["wheat_bag"] = { label = "Wheat Sac" },
    ["wheat_seed"] = { label = "Wheat Graine" },
}
