-- [fishing]
return {
    ["antipatharia_coral"] = { label = "Antipatharia Coral" },
    ["atum"] = { label = "Atum" },
    ["baleia"] = { label = "Baleia" },
    ["dendrogyra_coral"] = { label = "Dendrogyra Coral" },
    ["fishbait"] = { label = "Fishbait" },
    ["fishbaitillegal"] = { label = "Fishbaitillegal" },
    ["fishicebox"] = { label = "Fishicebox" },
    ["fishing_net1"] = { label = "Fishing Net1" },
    ["fishing_rod1"] = { label = "Fishing Rod1" },
    ["fishing_rod2"] = { label = "Fishing Rod2" },
    ["fishing_rod3"] = { label = "Fishing Rod3" },
    ["fishing_rod4"] = { label = "Fishing Rod4" },
    ["fishtacklebox"] = { label = "Fishtacklebox" },
    ["golfinho"] = { label = "Golfinho" },
    ["o_anchovy"] = { label = "Anchovy" },
    ["o_codfish"] = { label = "Codfish" },
    ["o_giant_seabass"] = { label = "Giant Seabass" },
    ["o_grouper"] = { label = "Grouper" },
    ["o_kingcrab"] = { label = "Kingcrab" },
    ["o_lobster"] = { label = "Homard" },
    ["o_mackerel"] = { label = "Mackerel" },
    ["o_mahi_mahi"] = { label = "Mahi Mahi" },
    ["o_pacific_halibut"] = { label = "Pacific Halibut" },
    ["o_pacific_sardine"] = { label = "Pacific Sardine" },
    ["o_rainbow_trout"] = { label = "Rainbow Trout" },
    ["o_red_snapper"] = { label = "Rouge Snapper" },
    ["o_redfish"] = { label = "Redfish" },
    ["o_spot_prawn"] = { label = "Spot Prawn" },
    ["o_stingray"] = { label = "Stingray" },
    ["o_white_seabass"] = { label = "Blanc Seabass" },
    ["o_yellowfin_tuna"] = { label = "Yellowfin Thon" },
    ["peixegato"] = { label = "Peixegato" },
    ["r_black_crappie"] = { label = "Black Crappie" },
    ["r_bluegill"] = { label = "Bluegill" },
    ["r_brown_trout"] = { label = "Brown Trout" },
    ["r_catfish"] = { label = "Catfish" },
    ["r_chinook_salmon"] = { label = "Chinook Saumon" },
    ["r_coho_salmon"] = { label = "Coho Saumon" },
    ["r_common_carp"] = { label = "Common Carp" },
    ["r_cutthroat_trout"] = { label = "Cutthroat Trout" },
    ["r_largemouth_bass"] = { label = "Largemouth Bass" },
    ["r_perch"] = { label = "Perch" },
    ["r_striped_bass"] = { label = "Striped Bass" },
    ["r_talapia"] = { label = "Talapia" },
    ["r_white_sturgeon"] = { label = "Blanc Sturgeon" },
}
