-- [food]
return {
    ["alla"] = { label = "Alla" },
    ["americancheese"] = { label = "Americancheese" },
    ["bacalhaucozido"] = { label = "Bacalhaucozido" },
    ["bacon"] = { label = "Bacon" },
    ["baconburger"] = { label = "Baconburger" },
    ["baconcheesemelt"] = { label = "Baconcheesemelt" },
    ["baconegg"] = { label = "Baconegg" },
    ["baconroll"] = { label = "Baconroll" },
    ["banana"] = { label = "Banana" },
    ["bangers"] = { label = "Bangers" },
    ["baquette"] = { label = "Baquette" },
    ["base2"] = { label = "Base2" },
    ["basil"] = { label = "Basil" },
    ["beef_jerky"] = { label = "Beef Jerky" },
    ["bento"] = { label = "Bento" },
    ["bento2"] = { label = "Bento2" },
    ["bento3"] = { label = "Bento3" },
    ["bento4"] = { label = "Bento4" },
    ["bento5"] = { label = "Bento5" },
    ["bento6"] = { label = "Bento6" },
    ["boba"] = { label = "Boba" },
    ["bolognese"] = { label = "Bolognese" },
    ["box_chocolate"] = { label = "Boîte Chocolat" },
    ["box_meat"] = { label = "Boîte Viande" },
    ["box_seafood"] = { label = "Boîte Seafood" },
    ["bplate"] = { label = "Bplate" },
    ["breadslice"] = { label = "Breadslice" },
    ["bs_bun"] = { label = "Bs Bun" },
    ["bs_patty_raw"] = { label = "Bs Patty Cru" },
    ["burger-bleeder"] = { label = "Burger Bleeder" },
    ["burger-chickenmelt"] = { label = "Burger Chickenmelt" },
    ["burger-chickenwrap"] = { label = "Burger Chickenwrap" },
    ["burger-creampie"] = { label = "Burger Creampie" },
    ["burger-frozennugget"] = { label = "Burger Frozennugget" },
    ["burger-goatwrap"] = { label = "Burger Goatwrap" },
    ["burger-heartstopper"] = { label = "Burger Heartstopper" },
    ["burger-icecream-empty"] = { label = "Burger Icecream Vide" },
    ["burger-icecream"] = { label = "Burger Icecream" },
    ["burger-icecream2"] = { label = "Burger Icecream2" },
    ["burger-meatfree"] = { label = "Burger Meatfree" },
    ["burger-milk"] = { label = "Burger Lait" },
    ["burger-milkshake"] = { label = "Burger Milkshake" },
    ["burger-moneyshot"] = { label = "Burger Moneyshot" },
    ["burger-onion"] = { label = "Burger Onion" },
    ["burger-rimjob"] = { label = "Burger Rimjob" },
    ["burger-slicedonion"] = { label = "Burger Slicedonion" },
    ["burger-slicedpotato"] = { label = "Burger Slicedpotato" },
    ["burger-torpedo"] = { label = "Burger Torpedo" },
    ["burger"] = { label = "Burger" },
    ["burgerbun"] = { label = "Burgerbun" },
    ["burgermeat"] = { label = "Burgermeat" },
    ["burgerpatty"] = { label = "Burgerpatty" },
    ["burrito"] = { label = "Burrito" },
    ["cake1"] = { label = "Cake1" },
    ["cake2"] = { label = "Cake2" },
    ["cake3"] = { label = "Cake3" },
    ["cake4"] = { label = "Cake4" },
    ["cake_birthday1"] = { label = "Gâteau Birthday1" },
    ["cake_birthday2"] = { label = "Gâteau Birthday2" },
    ["cake_carrot"] = { label = "Gâteau Carrot" },
    ["cake_chocolate"] = { label = "Gâteau Chocolat" },
    ["cake_pineapple"] = { label = "Gâteau Pineapple" },
    ["cake_redvelvet"] = { label = "Gâteau Redvelvet" },
    ["cake_slice1"] = { label = "Gâteau Slice1" },
    ["cake_slice2"] = { label = "Gâteau Slice2" },
    ["cake_slice3"] = { label = "Gâteau Slice3" },
    ["cake_slice4"] = { label = "Gâteau Slice4" },
    ["cake_strawberry"] = { label = "Gâteau Strawberry" },
    ["cake_wedding1"] = { label = "Gâteau Wedding1" },
    ["cake_wedding2"] = { label = "Gâteau Wedding2" },
    ["cake_wedding3"] = { label = "Gâteau Wedding3" },
    ["cake_wedding4"] = { label = "Gâteau Wedding4" },
    ["cake_wedding5"] = { label = "Gâteau Wedding5" },
    ["cakepop"] = { label = "Cakepop" },
    ["cakepop2"] = { label = "Cakepop2" },
    ["cakepop3"] = { label = "Cakepop3" },
    ["cakepop4"] = { label = "Cakepop4" },
    ["candied_bacon"] = { label = "Candied Bacon" },
    ["candy1"] = { label = "Candy1" },
    ["candy2"] = { label = "Candy2" },
    ["candy_cane"] = { label = "Candy Cane" },
    ["candy_gummies"] = { label = "Candy Gummies" },
    ["candy_hard"] = { label = "Candy Hard" },
    ["candy_suckerb"] = { label = "Candy Suckerb" },
    ["candy_suckerg"] = { label = "Candy Suckerg" },
    ["candy_suckero"] = { label = "Candy Suckero" },
    ["candy_suckerp"] = { label = "Candy Suckerp" },
    ["candy_suckerr"] = { label = "Candy Suckerr" },
    ["cataccino"] = { label = "Cataccino" },
    ["catcookie"] = { label = "Catcookie" },
    ["catdonut"] = { label = "Catdonut" },
    ["catlatte"] = { label = "Catlatte" },
    ["catpizza"] = { label = "Catpizza" },
    ["catrice"] = { label = "Catrice" },
    ["cavalacozida"] = { label = "Cavalacozida" },
    ["cheddar"] = { label = "Cheddar" },
    ["cheeseburger"] = { label = "Cheeseburger" },
    ["cheesecake"] = { label = "Cheesecake" },
    ["chickenbreast"] = { label = "Chickenbreast" },
    ["chickenburger"] = { label = "Chickenburger" },
    ["chickenfaj"] = { label = "Chickenfaj" },
    ["chickenpie"] = { label = "Chickenpie" },
    ["chickensalad"] = { label = "Chickensalad" },
    ["chickensandwich"] = { label = "Chickensandwich" },
    ["chickenthighs"] = { label = "Chickenthighs" },
    ["chickenthing"] = { label = "Chickenthing" },
    ["chickhornstars"] = { label = "Chickhornstars" },
    ["chillimince"] = { label = "Chillimince" },
    ["chocolate1"] = { label = "Chocolate1" },
    ["chocolate10"] = { label = "Chocolate10" },
    ["chocolate2"] = { label = "Chocolate2" },
    ["chocolate3"] = { label = "Chocolate3" },
    ["chocolate4"] = { label = "Chocolate4" },
    ["chocolate5"] = { label = "Chocolate5" },
    ["chocolate6"] = { label = "Chocolate6" },
    ["chocolate7"] = { label = "Chocolate7" },
    ["chocolate8"] = { label = "Chocolate8" },
    ["chocolate9"] = { label = "Chocolate9" },
    ["chocpudding"] = { label = "Chocpudding" },
    ["churros"] = { label = "Churros" },
    ["coffee_generic"] = { label = "Coffee Generic" },
    ["coffee_generic2"] = { label = "Coffee Generic2" },
    ["coffee_generic3"] = { label = "Coffee Generic3" },
    ["coldweiner"] = { label = "Coldweiner" },
    ["cone_blueberry"] = { label = "Cone Blueberry" },
    ["cone_chocolate2"] = { label = "Cone Chocolate2" },
    ["cone_pistachio"] = { label = "Cone Pistachio" },
    ["cone_strawberry"] = { label = "Cone Strawberry" },
    ["cone_vanilla"] = { label = "Cone Vanilla" },
    ["cookie"] = { label = "Cookie" },
    ["cooking_chocolate"] = { label = "Cooking Chocolat" },
    ["cubasil"] = { label = "Cubasil" },
    ["cucumber"] = { label = "Cucumber" },
    ["cupcake_blue"] = { label = "Cupcake Blue" },
    ["cupcake_cherry"] = { label = "Cupcake Cherry" },
    ["cupcake_chocolate"] = { label = "Cupcake Chocolat" },
    ["cupcake_confetti"] = { label = "Cupcake Confetti" },
    ["cupcake_creamcheese"] = { label = "Cupcake Creamcheese" },
    ["cupcake_pistachio"] = { label = "Cupcake Pistachio" },
    ["cupcake_rainbow"] = { label = "Cupcake Rainbow" },
    ["cupcake_vanilla"] = { label = "Cupcake Vanilla" },
    ["dbl_hornburger"] = { label = "Dbl Hornburger" },
    ["dimsum1"] = { label = "Dimsum1" },
    ["dimsum2"] = { label = "Dimsum2" },
    ["dimsum3"] = { label = "Dimsum3" },
    ["dimsum4"] = { label = "Dimsum4" },
    ["dimsum5"] = { label = "Dimsum5" },
    ["dimsum6"] = { label = "Dimsum6" },
    ["donut1"] = { label = "Donut1" },
    ["donut10"] = { label = "Donut10" },
    ["donut11"] = { label = "Donut11" },
    ["donut2"] = { label = "Donut2" },
    ["donut3"] = { label = "Donut3" },
    ["donut4"] = { label = "Donut4" },
    ["donut5"] = { label = "Donut5" },
    ["donut6"] = { label = "Donut6" },
    ["donut7"] = { label = "Donut7" },
    ["donut8"] = { label = "Donut8" },
    ["donut9"] = { label = "Donut9" },
    ["durum1"] = { label = "Durum1" },
    ["durum2"] = { label = "Durum2" },
    ["durum3"] = { label = "Durum3" },
    ["durum4"] = { label = "Durum4" },
    ["durum5"] = { label = "Durum5" },
    ["durum6"] = { label = "Durum6" },
    ["durum7"] = { label = "Durum7" },
    ["eggbene"] = { label = "Eggbene" },
    ["eggs"] = { label = "Eggs" },
    ["emptymilkbottle"] = { label = "Emptymilkbottle" },
    ["enchi"] = { label = "Enchi" },
    ["enchilada"] = { label = "Enchilada" },
    ["fakecrab"] = { label = "Fakecrab" },
    ["farming_butter"] = { label = "Farming Butter" },
    ["farming_chickenbreast"] = { label = "Farming Chickenbreast" },
    ["farming_tomato"] = { label = "Farming Tomato" },
    ["fish_fillet"] = { label = "Poisson Fillet" },
    ["flour"] = { label = "Flour" },
    ["frenchfries_generic"] = { label = "Frenchfries Generic" },
    ["frenchtoast"] = { label = "Frenchtoast" },
    ["frenchtoast2"] = { label = "Frenchtoast2" },
    ["friedpick"] = { label = "Friedpick" },
    ["fries_gravy_cheese"] = { label = "Fries Gravy Fromage" },
    ["fruit_smoothie"] = { label = "Fruit Smoothie" },
    ["fruittart"] = { label = "Fruittart" },
    ["fruittart2"] = { label = "Fruittart2" },
    ["gelato"] = { label = "Gelato" },
    ["gp_salad"] = { label = "Gp Salad" },
    ["gp_soup_salad_sandwich_combo"] = { label = "Gp Soupe Salad Sandwich Combo" },
    ["gp_strawberry_shortcake"] = { label = "Gp Strawberry Shortcake" },
    ["grape"] = { label = "Grape" },
    ["grilled_wrap"] = { label = "Grilled Wrap" },
    ["ham"] = { label = "Ham" },
    ["hamburger"] = { label = "Hamburger" },
    ["hashbrown"] = { label = "Hashbrown" },
    ["hornburger"] = { label = "Hornburger" },
    ["hornsandwich"] = { label = "Hornsandwich" },
    ["hotdog_chili"] = { label = "Hotdog Chili" },
    ["hotdog_chillicheesedog"] = { label = "Hotdog Chillicheesedog" },
    ["hotdog_deluxe"] = { label = "Hotdog Deluxe" },
    ["hotdog_ketchup"] = { label = "Hotdog Ketchup" },
    ["hotdog_mustard"] = { label = "Hotdog Mustard" },
    ["hotdog_plain"] = { label = "Hotdog Plain" },
    ["hotdog_taco"] = { label = "Hotdog Taco" },
    ["hotdog_veggie"] = { label = "Hotdog Veggie" },
    ["hotdogbun"] = { label = "Hotdogbun" },
    ["hotdogmeat"] = { label = "Hotdogmeat" },
    ["ice_bag"] = { label = "Ice Sac" },
    ["ice_cup"] = { label = "Ice Cup" },
    ["instantcoffee"] = { label = "Instantcoffee" },
    ["jello"] = { label = "Jello" },
    ["juice_apple"] = { label = "Juice Apple" },
    ["juice_cranberry"] = { label = "Juice Cranberry" },
    ["juice_grape"] = { label = "Juice Grape" },
    ["juice_pineapple"] = { label = "Juice Pineapple" },
    ["kebab1"] = { label = "Kebab1" },
    ["kebab2"] = { label = "Kebab2" },
    ["kebab3"] = { label = "Kebab3" },
    ["kebab4"] = { label = "Kebab4" },
    ["lemonade"] = { label = "Lemonade" },
    ["loaded_burger"] = { label = "Loaded Burger" },
    ["maccheese"] = { label = "Maccheese" },
    ["matcha"] = { label = "Matcha" },
    ["meatball"] = { label = "Meatball" },
    ["medfruits"] = { label = "Medfruits" },
    ["mint"] = { label = "Mint" },
    ["miso"] = { label = "Miso" },
    ["mochameow"] = { label = "Mochameow" },
    ["mochiblue"] = { label = "Mochiblue" },
    ["mochigreen"] = { label = "Mochigreen" },
    ["mochiorange"] = { label = "Mochiorange" },
    ["mochipink"] = { label = "Mochipink" },
    ["mozz"] = { label = "Mozz" },
    ["nacho_plate"] = { label = "Nacho Plate" },
    ["nachos"] = { label = "Nachos" },
    ["noodlebowl"] = { label = "Noodlebowl" },
    ["noodles"] = { label = "Nouille" },
    ["nori"] = { label = "Nori" },
    ["olives"] = { label = "Olives" },
    ["pasta"] = { label = "Pasta" },
    ["pawcakes"] = { label = "Pawcakes" },
    ["pear"] = { label = "Pear" },
    ["pickle"] = { label = "Pickle" },
    ["pickleburger"] = { label = "Pickleburger" },
    ["piecrust"] = { label = "Piecrust" },
    ["pizza_cannabisvegetariana"] = { label = "Pizza Cannabisvegetariana" },
    ["pizza_capricciosa"] = { label = "Pizza Capricciosa" },
    ["pizza_diavola"] = { label = "Pizza Diavola" },
    ["pizza_margherita"] = { label = "Pizza Margherita" },
    ["pizza_marinara"] = { label = "Pizza Marinara" },
    ["pizza_proscuttio"] = { label = "Pizza Proscuttio" },
    ["pizza_vegetariana"] = { label = "Pizza Vegetariana" },
    ["pizzadough"] = { label = "Pizzadough" },
    ["potato_chips"] = { label = "Potato Chips" },
    ["pulledpork_sliders"] = { label = "Pulledpork Sliders" },
    ["pulledporksand"] = { label = "Pulledporksand" },
    ["purrito"] = { label = "Purrito" },
    ["ramen"] = { label = "Ramen" },
    ["ranchwrap"] = { label = "Ranchwrap" },
    ["rawbacon"] = { label = "Rawbacon" },
    ["rawhotdog"] = { label = "Rawhotdog" },
    ["rawsausage"] = { label = "Rawsausage" },
    ["ribs"] = { label = "Ribs" },
    ["rice"] = { label = "Riz" },
    ["rottenapple"] = { label = "Rottenapple" },
    ["sake"] = { label = "Sake" },
    ["salami"] = { label = "Salami" },
    ["sandwich_bacon"] = { label = "Sandwich Bacon" },
    ["sandwich_blt"] = { label = "Sandwich Blt" },
    ["sandwich_eggsalad"] = { label = "Sandwich Eggsalad" },
    ["sandwich_grilledcheese"] = { label = "Sandwich Grilledcheese" },
    ["sandwich_grilledcheese2"] = { label = "Sandwich Grilledcheese2" },
    ["sandwich_ham"] = { label = "Sandwich Ham" },
    ["sandwich_hamcheese"] = { label = "Sandwich Hamcheese" },
    ["sandwich_moldy"] = { label = "Sandwich Moldy" },
    ["sandwich_ruben"] = { label = "Sandwich Ruben" },
    ["sandwich_sub"] = { label = "Sandwich Sub" },
    ["sandwich_tuna"] = { label = "Sandwich Thon" },
    ["sausage"] = { label = "Sausage" },
    ["sausageeggs"] = { label = "Sausageeggs" },
    ["seafood_beerbatterfish"] = { label = "Seafood Beerbatterfish" },
    ["seafood_calamari"] = { label = "Seafood Calamari" },
    ["seafood_calamari2"] = { label = "Seafood Calamari2" },
    ["seafood_crabcakes"] = { label = "Seafood Crabcakes" },
    ["seafood_grilledfish"] = { label = "Seafood Grilledfish" },
    ["seafood_grilledsalmon"] = { label = "Seafood Grilledsalmon" },
    ["seafood_kingcrab"] = { label = "Seafood Kingcrab" },
    ["seafood_lobster"] = { label = "Seafood Homard" },
    ["seafood_lobster2"] = { label = "Seafood Lobster2" },
    ["seafood_paella"] = { label = "Seafood Paella" },
    ["seafood_pescatore"] = { label = "Seafood Pescatore" },
    ["seafood_salmon"] = { label = "Seafood Saumon" },
    ["seafood_sardines"] = { label = "Seafood Sardines" },
    ["seafood_seabass"] = { label = "Seafood Seabass" },
    ["seafood_shrimpcocktail"] = { label = "Seafood Shrimpcocktail" },
    ["seafood_shrimppasta"] = { label = "Seafood Shrimppasta" },
    ["shreddedpork"] = { label = "Shreddedpork" },
    ["slicedapple"] = { label = "Slicedapple" },
    ["slicedtomato"] = { label = "Slicedtomato" },
    ["slider"] = { label = "Slider" },
    ["soda_fruit_punch"] = { label = "Soda Fruit Punch" },
    ["soda_lime"] = { label = "Soda Lime" },
    ["soda_mandarin"] = { label = "Soda Mandarin" },
    ["soda_pineapple"] = { label = "Soda Pineapple" },
    ["soda_strawberry"] = { label = "Soda Strawberry" },
    ["sodasyrup"] = { label = "Sodasyrup" },
    ["soup_bean"] = { label = "Soupe Bean" },
    ["soup_broccoli"] = { label = "Soupe Broccoli" },
    ["soup_chickennoodle"] = { label = "Soupe Chickennoodle" },
    ["soup_chickenveg"] = { label = "Soupe Chickenveg" },
    ["soup_chickenveg2"] = { label = "Soupe Chickenveg2" },
    ["soup_clamchowder2"] = { label = "Soupe Clamchowder2" },
    ["soup_cornchowder"] = { label = "Soupe Cornchowder" },
    ["soup_creamypotato"] = { label = "Soupe Creamypotato" },
    ["soup_frenchonion"] = { label = "Soupe Frenchonion" },
    ["soup_frenchonion2"] = { label = "Soupe Frenchonion2" },
    ["soup_gazpacho"] = { label = "Soupe Gazpacho" },
    ["soup_miso"] = { label = "Soupe Miso" },
    ["soup_mushroom"] = { label = "Soupe Champignon" },
    ["soup_seafood"] = { label = "Soupe Seafood" },
    ["soup_squash"] = { label = "Soupe Squash" },
    ["soup_tomato"] = { label = "Soupe Tomato" },
    ["soup_tomato2"] = { label = "Soupe Tomato2" },
    ["soup_vegetable"] = { label = "Soupe Vegetable" },
    ["splate"] = { label = "Splate" },
    ["squid"] = { label = "Squid" },
    ["steakburger"] = { label = "Steakburger" },
    ["strawberryfloat"] = { label = "Strawberryfloat" },
    ["stuffedpotato"] = { label = "Stuffedpotato" },
    ["sugar"] = { label = "Sugar" },
    ["sunday_caramel"] = { label = "Sunday Caramel" },
    ["sunday_chocolate"] = { label = "Sunday Chocolat" },
    ["sunday_strawberry"] = { label = "Sunday Strawberry" },
    ["surimi"] = { label = "Surimi" },
    ["sushi1"] = { label = "Sushi1" },
    ["sushi10"] = { label = "Sushi10" },
    ["sushi11"] = { label = "Sushi11" },
    ["sushi2"] = { label = "Sushi2" },
    ["sushi3"] = { label = "Sushi3" },
    ["sushi4"] = { label = "Sushi4" },
    ["sushi5"] = { label = "Sushi5" },
    ["sushi6"] = { label = "Sushi6" },
    ["sushi7"] = { label = "Sushi7" },
    ["sushi8"] = { label = "Sushi8" },
    ["sushi9"] = { label = "Sushi9" },
    ["taco_beef"] = { label = "Taco Beef" },
    ["taco_chicken"] = { label = "Taco Poulet" },
    ["taco_chicken2"] = { label = "Taco Chicken2" },
    ["taco_fish"] = { label = "Taco Poisson" },
    ["taco_plate"] = { label = "Taco Plate" },
    ["taco_shell"] = { label = "Taco Shell" },
    ["tea_black"] = { label = "Tea Black" },
    ["tea_bubble"] = { label = "Tea Bubble" },
    ["tea_bubble_blue"] = { label = "Tea Bubble Blue" },
    ["tea_bubble_green"] = { label = "Tea Bubble Green" },
    ["tea_bubble_orange"] = { label = "Tea Bubble Orange" },
    ["tea_bubble_pink"] = { label = "Tea Bubble Pink" },
    ["tea_green"] = { label = "Tea Green" },
    ["tea_green_matcha"] = { label = "Tea Green Matcha" },
    ["tea_iced"] = { label = "Tea Iced" },
    ["tea_peach_ided"] = { label = "Tea Peach Ided" },
    ["teabag"] = { label = "Teabag" },
    ["tf_tostada"] = { label = "Tf Tostada" },
    ["tiramisu"] = { label = "Tiramisu" },
    ["tofu"] = { label = "Tofu" },
    ["tostada"] = { label = "Tostada" },
    ["tostada_shell"] = { label = "Tostada Shell" },
    ["tots"] = { label = "Tots" },
    ["tripleburger"] = { label = "Tripleburger" },
    ["uwu-cafe-box"] = { label = "Uwu Cafe Boîte" },
    ["uwu_bubbletea"] = { label = "Uwu Bubbletea" },
    ["veggiewrap"] = { label = "Veggiewrap" },
    ["water_bottle"] = { label = "Eau Bottle" },
    ["water_bottle2"] = { label = "Eau Bottle2" },
    ["water_bulk"] = { label = "Eau Bulk" },
    ["whip_cream"] = { label = "Whip Cream" },
    ["wings"] = { label = "Wings" },
    ["wrap"] = { label = "Wrap" },
}
