-- [garage]
return {
    ["accesstool"] = { label = "Accesstool" },
    ["advancedkit"] = { label = "Advancedkit" },
    ["anchor"] = { label = "Anchor" },
    ["anglegrinder"] = { label = "Anglegrinder" },
    ["armour"] = { label = "Armour" },
    ["beltcutter"] = { label = "Beltcutter" },
    ["bprooftires"] = { label = "Bprooftires" },
    ["brakes1"] = { label = "Brakes1" },
    ["brakes2"] = { label = "Brakes2" },
    ["brakes3"] = { label = "Brakes3" },
    ["bumper"] = { label = "Bumper" },
    ["carjack"] = { label = "Carjack" },
    ["carstereo"] = { label = "Carstereo" },
    ["cleaningkit"] = { label = "Cleaningkit" },
    ["cutter"] = { label = "Cutter" },
    ["drifttires"] = { label = "Drifttires" },
    ["exhaust"] = { label = "Exhaust" },
    ["harness"] = { label = "Harness" },
    ["headlights"] = { label = "Headlights" },
    ["hood"] = { label = "Hood" },
    ["horn"] = { label = "Horn" },
    ["livery"] = { label = "Livery" },
    ["mechanic_tools"] = { label = "Mechanic Tools" },
    ["mechboard"] = { label = "Mechboard" },
    ["mirror"] = { label = "Mirror" },
    ["nitrogen"] = { label = "Nitrogen" },
    ["nitrous"] = { label = "Nitrous" },
    ["pwasher"] = { label = "Pwasher" },
    ["repairkit"] = { label = "Repairkit" },
    ["rifle_drummag"] = { label = "Fusil Drummag" },
    ["rim"] = { label = "Rim" },
    ["rims"] = { label = "Rims" },
    ["rollcage"] = { label = "Rollcage" },
    ["roof"] = { label = "Roof" },
    ["seat"] = { label = "Seat" },
    ["shonen"] = { label = "Shonen" },
    ["skirts"] = { label = "Skirts" },
    ["spanner"] = { label = "Spanner" },
    ["spoiler"] = { label = "Spoiler" },
    ["spray"] = { label = "Spray" },
    ["spray_remover"] = { label = "Spray Remover" },
    ["suspension1"] = { label = "Suspension1" },
    ["suspension2"] = { label = "Suspension2" },
    ["suspension3"] = { label = "Suspension3" },
    ["suspension4"] = { label = "Suspension4" },
    ["tint_supplies"] = { label = "Tint Supplies" },
    ["tires"] = { label = "Tires" },
    ["toolbox"] = { label = "Toolbox" },
    ["transmission1"] = { label = "Transmission1" },
    ["transmission2"] = { label = "Transmission2" },
    ["transmission3"] = { label = "Transmission3" },
    ["tunerchip"] = { label = "Tunerchip" },
    ["turbo"] = { label = "Turbo" },
    ["tyre_bennys"] = { label = "Tyre Bennys" },
    ["tyre_bespoke"] = { label = "Tyre Bespoke" },
    ["tyre_f1"] = { label = "Tyre F1" },
    ["tyre_highend"] = { label = "Tyre Highend" },
    ["tyre_lowrider"] = { label = "Tyre Lowrider" },
    ["tyre_motorcycle"] = { label = "Tyre Motorcycle" },
    ["tyre_muscle"] = { label = "Tyre Muscle" },
    ["tyre_offroad"] = { label = "Tyre Offroad" },
    ["tyre_sport"] = { label = "Tyre Sport" },
    ["tyre_street"] = { label = "Tyre Street" },
    ["tyre_suv"] = { label = "Tyre Suv" },
    ["tyre_tuner"] = { label = "Tyre Tuner" },
    ["underglow_controller"] = { label = "Underglow Controller" },
    ["v10engine"] = { label = "V10engine" },
    ["v12engine"] = { label = "V12engine" },
    ["v8engine"] = { label = "V8engine" },
}
