-- [hunting]
return {
    ["boar_tusks"] = { label = "Boar Tusks" },
    ["cougar_claw"] = { label = "Cougar Claw" },
    ["cowpelt"] = { label = "Cowpelt" },
    ["coyote_teeth"] = { label = "Coyote Teeth" },
    ["coyotepelt"] = { label = "Coyotepelt" },
    ["deer_horns"] = { label = "Deer Horns" },
    ["hunting_ammo"] = { label = "Hunting Ammo" },
    ["hunting_rifle"] = { label = "Hunting Fusil" },
    ["huntingbait"] = { label = "Huntingbait" },
    ["meat"] = { label = "Viande" },
    ["meat_boar"] = { label = "Viande Boar" },
    ["meat_chicken"] = { label = "Viande Poulet" },
    ["meat_chickenhawk"] = { label = "Viande Chickenhawk" },
    ["meat_cormorant"] = { label = "Viande Cormorant" },
    ["meat_cougar"] = { label = "Viande Cougar" },
    ["meat_cow"] = { label = "Viande Cow" },
    ["meat_coyote"] = { label = "Viande Coyote" },
    ["meat_deer"] = { label = "Viande Deer" },
    ["meat_dolphin"] = { label = "Viande Dolphin" },
    ["meat_mtlion"] = { label = "Viande Mtlion" },
    ["meat_pig"] = { label = "Viande Pig" },
    ["meat_rabbit"] = { label = "Viande Rabbit" },
    ["meat_rat"] = { label = "Viande Rat" },
    ["meat_shark"] = { label = "Viande Shark" },
    ["meat_stingray"] = { label = "Viande Stingray" },
    ["meat_whale"] = { label = "Viande Whale" },
    ["pigpelt"] = { label = "Pigpelt" },
    ["rabbit_foot"] = { label = "Rabbit Foot" },
    ["rabbitfur"] = { label = "Rabbitfur" },
    ["skin_boar"] = { label = "Skin Boar" },
    ["skin_cougar"] = { label = "Skin Cougar" },
    ["skin_deer"] = { label = "Skin Deer" },
    ["skin_dolphin"] = { label = "Skin Dolphin" },
    ["skin_mtlion"] = { label = "Skin Mtlion" },
    ["skin_pig"] = { label = "Skin Pig" },
    ["skin_rabbit"] = { label = "Skin Rabbit" },
    ["skin_rat"] = { label = "Skin Rat" },
    ["skin_sasquatch"] = { label = "Skin Sasquatch" },
    ["skin_shark"] = { label = "Skin Shark" },
    ["skin_stingray"] = { label = "Skin Stingray" },
    ["skin_whale"] = { label = "Skin Whale" },
}
