-- [jewelry]
return {
    ["10kgoldchain"] = { label = "10kgoldchain" },
    ["diamond_earring"] = { label = "Diamond Earring" },
    ["diamond_earring_silver"] = { label = "Diamond Earring Silver" },
    ["diamond_necklace"] = { label = "Diamond Necklace" },
    ["diamond_necklace_silver"] = { label = "Diamond Necklace Silver" },
    ["diamond_ring"] = { label = "Diamond Ring" },
    ["diamond_ring_silver"] = { label = "Diamond Ring Silver" },
    ["emerald_earring"] = { label = "Emerald Earring" },
    ["emerald_earring_silver"] = { label = "Emerald Earring Silver" },
    ["emerald_necklace"] = { label = "Emerald Necklace" },
    ["emerald_necklace_silver"] = { label = "Emerald Necklace Silver" },
    ["emerald_ring"] = { label = "Emerald Ring" },
    ["emerald_ring_silver"] = { label = "Emerald Ring Silver" },
    ["gold_earring"] = { label = "Gold Earring" },
    ["gold_ring"] = { label = "Gold Ring" },
    ["goldchain"] = { label = "Goldchain" },
    ["goldchain2"] = { label = "Goldchain2" },
    ["ruby_earring"] = { label = "Ruby Earring" },
    ["ruby_earring_silver"] = { label = "Ruby Earring Silver" },
    ["ruby_necklace"] = { label = "Ruby Necklace" },
    ["ruby_necklace_silver"] = { label = "Ruby Necklace Silver" },
    ["ruby_ring"] = { label = "Ruby Ring" },
    ["ruby_ring_silver"] = { label = "Ruby Ring Silver" },
    ["sapphire_earring"] = { label = "Sapphire Earring" },
    ["sapphire_earring_silver"] = { label = "Sapphire Earring Silver" },
    ["sapphire_necklace"] = { label = "Sapphire Necklace" },
    ["sapphire_necklace_silver"] = { label = "Sapphire Necklace Silver" },
    ["sapphire_ring"] = { label = "Sapphire Ring" },
    ["sapphire_ring_silver"] = { label = "Sapphire Ring Silver" },
    ["silver_earring"] = { label = "Silver Earring" },
    ["silver_ring"] = { label = "Silver Ring" },
    ["silverchain"] = { label = "Silverchain" },
}
