-- [mining]
return {
    ["Steel ingot"] = { label = "Steel ingot" },
    ["carbon"] = { label = "Carbon" },
    ["copperore"] = { label = "Copperore" },
    ["diamond"] = { label = "Diamond" },
    ["emerald"] = { label = "Emerald" },
    ["goldingot"] = { label = "Goldingot" },
    ["goldore"] = { label = "Goldore" },
    ["goldpan"] = { label = "Goldpan" },
    ["ironingot"] = { label = "Ironingot" },
    ["ironore"] = { label = "Ironore" },
    ["miningdrill"] = { label = "Miningdrill" },
    ["mininglaser"] = { label = "Mininglaser" },
    ["pickaxe"] = { label = "Pickaxe" },
    ["ruby"] = { label = "Ruby" },
    ["sapphire"] = { label = "Sapphire" },
    ["silveringot"] = { label = "Silveringot" },
    ["silverore"] = { label = "Silverore" },
    ["stone"] = { label = "Stone" },
    ["uncut_diamond"] = { label = "Uncut Diamond" },
    ["uncut_emerald"] = { label = "Uncut Emerald" },
    ["uncut_ruby"] = { label = "Uncut Ruby" },
    ["uncut_sapphire"] = { label = "Uncut Sapphire" },
}
