-- [misc]
return {
    ["aceofhearts"] = { label = "Aceofhearts" },
    ["backpack4"] = { label = "Backpack4" },
    ["backpack5"] = { label = "Backpack5" },
    ["blueprint"] = { label = "Blueprint" },
    ["bmx"] = { label = "Bmx" },
    ["box_empty"] = { label = "Boîte Vide" },
    ["carkeys"] = { label = "Carkeys" },
    ["carkeys2"] = { label = "Carkeys2" },
    ["casino_chips_100"] = { label = "Casino Chips 100" },
    ["casino_chips_50"] = { label = "Casino Chips 50" },
    ["casino_chips_500"] = { label = "Casino Chips 500" },
    ["casino_chips_blu"] = { label = "Casino Chips Blu" },
    ["casino_chips_red"] = { label = "Casino Chips Rouge" },
    ["casino_chips_yel"] = { label = "Casino Chips Yel" },
    ["cigar"] = { label = "Cigare" },
    ["cigar_estancia"] = { label = "Cigare Estancia" },
    ["cigarette"] = { label = "Cigarette" },
    ["cigarette2"] = { label = "Cigarette2" },
    ["diving_gear"] = { label = "Diving Gear" },
    ["jerry_can"] = { label = "Jerry Canette" },
    ["key1"] = { label = "Key1" },
    ["key2"] = { label = "Key2" },
    ["key3"] = { label = "Key3" },
    ["lighter"] = { label = "Lighter" },
    ["lighter2"] = { label = "Lighter2" },
    ["lottery_ticket"] = { label = "Lottery Ticket" },
    ["newspaper"] = { label = "Newspaper" },
    ["parachute"] = { label = "Parachute" },
    ["printed_image"] = { label = "Printed Image" },
    ["reciept1"] = { label = "Reciept1" },
    ["reciept2"] = { label = "Reciept2" },
    ["scratch_ticket"] = { label = "Scratch Ticket" },
    ["scratch_ticket2"] = { label = "Scratch Ticket2" },
    ["skateboard"] = { label = "Skateboard" },
    ["stickynote"] = { label = "Stickynote" },
    ["umbrella"] = { label = "Umbrella" },
    ["vehiclecoupon"] = { label = "Vehiclecoupon" },
    ["wood"] = { label = "Wood" },
}
