-- [weapons]
return {
    ["binoculars"] = { label = "Binoculars" },
    ["mg_ammo"] = { label = "Mg Ammo" },
    ["nvg"] = { label = "Nvg" },
    ["pistol_ammo"] = { label = "Pistol Ammo" },
    ["pistol_extendedclip"] = { label = "Pistol Extendedclip" },
    ["pistol_suppressor"] = { label = "Pistol Suppressor" },
    ["rifle_ammo"] = { label = "Fusil Ammo" },
    ["shotgun_ammo"] = { label = "Shotgun Ammo" },
    ["smg_ammo"] = { label = "Smg Ammo" },
    ["smg_flashlight"] = { label = "Smg Flashlight" },
    ["smg_scope"] = { label = "Smg Scope" },
    ["thermal_katana_orange"] = { label = "Thermal Katana Orange" },
    ["weapon_briefcase"] = { label = "Weapon Briefcase" },
    ["weapon_briefcase2"] = { label = "Weapon Briefcase2" },
    ["weapon_flashlight"] = { label = "Weapon Flashlight" },
    ["weapon_garbagebag"] = { label = "Weapon Garbagebag" },
    ["weapon_goodnightbat"] = { label = "Weapon Goodnightbat" },
    ["weapon_hammer"] = { label = "Weapon Hammer" },
    ["weapon_handcuffs"] = { label = "Weapon Handcuffs" },
    ["weapon_knuckle"] = { label = "Weapon Knuckle" },
    ["weapon_lovehate"] = { label = "Weapon Lovehate" },
    ["weapon_nightstick"] = { label = "Weapon Nightstick" },
    ["weaponthreading"] = { label = "Weaponthreading" },
    ["weapontint_army"] = { label = "Weapontint Army" },
    ["weapontint_black"] = { label = "Weapontint Black" },
    ["weapontint_gold"] = { label = "Weapontint Gold" },
    ["weapontint_green"] = { label = "Weapontint Green" },
    ["weapontint_lspd"] = { label = "Weapontint Lspd" },
    ["weapontint_orange"] = { label = "Weapontint Orange" },
    ["weapontint_pink"] = { label = "Weapontint Pink" },
    ["weapontint_plat"] = { label = "Weapontint Plat" },
    ["zipties"] = { label = "Zipties" },
    ["zipties2"] = { label = "Zipties2" },
}
