return {
    -- [Alcohol]
    ["7and7"] = { label = "7and7" },
    ["amaretto"] = { label = "Amaretto" },
    ["amarone"] = { label = "Amarone" },
    ["beerglass"] = { label = "Beerglass" },
    ["beerglass2"] = { label = "Beerglass2" },
    ["beerglass3"] = { label = "Beerglass3" },
    ["bellini"] = { label = "Bellini" },
    ["blackrussian"] = { label = "Blackrussian" },
    ["bloodymary"] = { label = "Bloodymary" },
    ["bluekamikaze"] = { label = "Bluekamikaze" },
    ["champagne"] = { label = "Champagne" },
    ["cosmopolitan"] = { label = "Cosmopolitan" },
    ["curaco"] = { label = "Curaco" },
    ["daquirimint"] = { label = "Daquirimint" },
    ["daquiristraw"] = { label = "Daquiristraw" },
    ["drimartini"] = { label = "Drimartini" },
    ["gin"] = { label = "Gin" },
    ["gin2"] = { label = "Gin2" },
    ["gin_and_tonic"] = { label = "Gin et Tonic" },
    ["irishcream"] = { label = "Irishcream" },
    ["kamikaze"] = { label = "Kamikaze" },
    ["longisland"] = { label = "Longisland" },
    ["maitai"] = { label = "Maitai" },
    ["manhattin"] = { label = "Manhattin" },
    ["margarita"] = { label = "Margarita" },
    ["margaritacuraco"] = { label = "Margaritacuraco" },
    ["margaritastraw"] = { label = "Margaritastraw" },
    ["midori"] = { label = "Midori" },
    ["mimosa"] = { label = "Mimosa" },
    ["mojito"] = { label = "Mojito" },
    ["negroni"] = { label = "Negroni" },
    ["oldfashioned"] = { label = "Oldfashioned" },
    ["pinacolada"] = { label = "Pinacolada" },
    ["rosso"] = { label = "Rosso" },
    ["rum"] = { label = "Rum" },
    ["rum_and_cola"] = { label = "Rum et Cola" },
    ["sangria"] = { label = "Sangria" },
    ["schnapps"] = { label = "Schnapps" },
    ["scotch"] = { label = "Scotch" },
    ["screwdriver"] = { label = "Screwdriver" },
    ["shirleytemple"] = { label = "Shirleytemple" },
    ["shooter_applepie"] = { label = "Shooter Applepie" },
    ["shooter_b52"] = { label = "Shooter B52" },
    ["shooter_ccookie"] = { label = "Shooter Ccookie" },
    ["shooter_coffee_liqure"] = { label = "Shooter Coffee Liqure" },
    ["shooter_electricjello_blue"] = { label = "Shooter Electricjello Blue" },
    ["shooter_electricjello_lime"] = { label = "Shooter Electricjello Lime" },
    ["shooter_electricjello_red"] = { label = "Shooter Electricjello Rouge" },
    ["shooter_irishflag"] = { label = "Shooter Irishflag" },
    ["shooter_sbullet"] = { label = "Shooter Sbullet" },
    ["shooter_tequila"] = { label = "Shooter Tequila" },
    ["shooter_voodoo"] = { label = "Shooter Voodoo" },
    ["shooter_whiskey"] = { label = "Shooter Whiskey" },
    ["singaporesling"] = { label = "Singaporesling" },
    ["sour_amaretto"] = { label = "Sour Amaretto" },
    ["sour_whiskey"] = { label = "Sour Whiskey" },
    ["tequila"] = { label = "Tequila" },
    ["tomcollins"] = { label = "Tomcollins" },
    ["triplesec"] = { label = "Triplesec" },
    ["vodka"] = { label = "Vodka" },
    ["whiskey"] = { label = "Whiskey" },
    ["whiskey_rocks"] = { label = "Whiskey Rocks" },
    ["wine_barbera"] = { label = "Vin Barbera" },
    ["wine_chardoney"] = { label = "Vin Chardoney" },
    ["wine_chardonnay"] = { label = "Vin Chardonnay" },
    ["wine_dolcetto"] = { label = "Vin Dolcetto" },
    ["wine_merlot"] = { label = "Vin Merlot" },
    ["wine_prosecco"] = { label = "Vin Prosecco" },
    ["wine_red"] = { label = "Vin Rouge" },
    ["wine_rose"] = { label = "Vin Rosé" },
    ["wine_white"] = { label = "Vin Blanc" },
    ["woowoo"] = { label = "Woowoo" },

    -- [Camping]
    ["beachtowel"] = { label = "Beachtowel" },
    ["campfire"] = { label = "Campfire" },
    ["cooler"] = { label = "Cooler" },
    ["firework1"] = { label = "Firework1" },
    ["firework2"] = { label = "Firework2" },
    ["firework3"] = { label = "Firework3" },
    ["firework4"] = { label = "Firework4" },
    ["firework5"] = { label = "Firework5" },
    ["fogueira"] = { label = "Fogueira" },

    -- [Crafting]
    ["aluminum"] = { label = "Aluminum" },
    ["bin_blue"] = { label = "Bin Blue" },
    ["bin_red"] = { label = "Bin Rouge" },
    ["bird_feather"] = { label = "Bird Feather" },
    ["bottle"] = { label = "Bottle" },
    ["bucket"] = { label = "Bucket" },
    ["butcherpaper"] = { label = "Butcherpaper" },
    ["can"] = { label = "Canette" },
    ["circuit_board"] = { label = "Circuit Board" },
    ["cloth"] = { label = "Cloth" },
    ["copper"] = { label = "Copper" },
    ["copper_wires"] = { label = "Copper Wires" },
    ["glass"] = { label = "Glass" },
    ["hammer"] = { label = "Hammer" },
    ["lithium_battery"] = { label = "Lithium Pile" },
    ["metalscrap"] = { label = "Metalscrap" },
    ["plastic"] = { label = "Plastic" },
    ["rolling_paper"] = { label = "Rolling Paper" },
    ["rolling_paper2"] = { label = "Rolling Paper2" },
    ["rope"] = { label = "Rope" },
    ["rubber"] = { label = "Rubber" },
    ["snspistol_part_1"] = { label = "Snspistol Part 1" },
    ["snspistol_part_2"] = { label = "Snspistol Part 2" },
    ["snspistol_part_3"] = { label = "Snspistol Part 3" },
    ["steel_plate"] = { label = "Steel Plate" },
    ["tape_duct"] = { label = "Tape Duct" },
    ["tape_electrical"] = { label = "Tape Electrical" },
    ["wood_cedar"] = { label = "Wood Cedar" },
    ["wood_maple"] = { label = "Wood Maple" },
    ["wood_oak"] = { label = "Wood Oak" },
    ["wood_pine"] = { label = "Wood Pine" },

    -- [Crime]
    ["1000bearerbond"] = { label = "1000bearerbond" },
    ["adress_book"] = { label = "Adress Book" },
    ["advancedlockpick"] = { label = "Advancedlockpick" },
    ["bag"] = { label = "Sac" },
    ["bomb"] = { label = "Bomb" },
    ["co2"] = { label = "Co2" },
    ["cryptostick"] = { label = "Cryptostick" },
    ["drill"] = { label = "Drill" },
    ["drillbit"] = { label = "Drillbit" },
    ["electronickit"] = { label = "Electronickit" },
    ["gasmask"] = { label = "Gasmask" },
    ["generator"] = { label = "Générateur" },
    ["gps_hacking_device"] = { label = "GPS Hacking Device" },
    ["hacking_device"] = { label = "Hacking Device" },
    ["hacking_device2"] = { label = "Hacking Device2" },
    ["handgun"] = { label = "Pistolet" },
    ["hardrive"] = { label = "Disque dur" },
    ["head_bag"] = { label = "Head Sac" },
    ["hlabs_chemicals"] = { label = "Hlabs Chemicals" },
    ["hlabs_formula"] = { label = "Hlabs Formula" },
    ["hydrochloricacid"] = { label = "Hydrochloricacid" },
    ["hydrogen"] = { label = "Hydrogen" },
    ["ironoxide"] = { label = "Ironoxide" },
    ["lockpick"] = { label = "Crochetage" },
    ["markedbills"] = { label = "Markedbills" },
    ["moneybag"] = { label = "Moneybag" },
    ["multitool"] = { label = "Multitool" },
    ["plate"] = { label = "Plate" },
    ["rolex"] = { label = "Rolex" },
    ["scale"] = { label = "Scale" },
    ["screwdriverset"] = { label = "Tournevis" },
    ["stolenmicro"] = { label = "Stolenmicro" },
    ["stolenstereo"] = { label = "Stolenstereo" },
    ["stolentv"] = { label = "Stolentv" },

    -- [Drugs]
    ["1gheroin"] = { label = "1gheroin" },
    ["Coca-leaves"] = { label = "Coca Leaves" },
    ["acapulcogold_leaf"] = { label = "Acapulcogold Leaf" },
    ["acapulcogold_seed"] = { label = "Acapulcogold Graine" },
    ["acapulcogold_trimmed_bud"] = { label = "Acapulcogold Trimmed Bud" },
    ["acapulcogold_untrimmed_bud"] = { label = "Acapulcogold Untrimmed Bud" },
    ["acetone"] = { label = "Acétone" },
    ["acetonebarrel"] = { label = "Acetonebarrel" },
    ["acyclovir"] = { label = "Acyclovir" },
    ["aluminumoxide"] = { label = "Aluminumoxide" },
    ["ammonia"] = { label = "Ammoniac" },
    ["ammonium_nitrate"] = { label = "Ammonium Nitrate" },
    ["ammoniumnitrate"] = { label = "Ammoniumnitrate" },
    ["ammoniumnitratebarrel"] = { label = "Ammoniumnitratebarrel" },
    ["babypowder"] = { label = "Babypowder" },
    ["baggy_cocaine"] = { label = "Sachet Cocaïne" },
    ["baggy_empty"] = { label = "Sachet Vide" },
    ["baggy_empty2"] = { label = "Sachet Empty2" },
    ["baggy_extasy"] = { label = "Sachet Extasy" },
    ["baggy_meth"] = { label = "Sachet Méthamphétamine" },
    ["baggy_methLG"] = { label = "Sachet Methlg" },
    ["baggy_weed"] = { label = "Sachet Weed" },
    ["beaker"] = { label = "Beaker" },
    ["big_scale"] = { label = "Big Scale" },
    ["blunt"] = { label = "Blunt" },
    ["bluntwrap"] = { label = "Bluntwrap" },
    ["brick_cocaine"] = { label = "Brick Cocaïne" },
    ["brick_cocaine2"] = { label = "Brick Cocaine2" },
    ["brick_meth"] = { label = "Brick Méthamphétamine" },
    ["brick_opium"] = { label = "Brick Opium" },
    ["brick_weed"] = { label = "Brick Weed" },
    ["cannabis"] = { label = "Cannabis" },
    ["cannibis"] = { label = "Cannibis" },
    ["chemicalmixer"] = { label = "Chemicalmixer" },
    ["cocaine"] = { label = "Cocaïne" },
    ["cocaineleaf"] = { label = "Cocaineleaf" },
    ["cocaleaf"] = { label = "Cocaleaf" },
    ["codeine"] = { label = "Codeine" },
    ["cokepackage"] = { label = "Cokepackage" },
    ["colombiangold_leaf"] = { label = "Colombiangold Leaf" },
    ["colombiangold_seed"] = { label = "Colombiangold Graine" },
    ["colombiangold_trimmed_bud"] = { label = "Colombiangold Trimmed Bud" },
    ["colombiangold_untrimmed_bud"] = { label = "Colombiangold Untrimmed Bud" },
    ["crack_baggy"] = { label = "Crack Sachet" },
    ["crackmixingagent"] = { label = "Crackmixingagent" },
    ["distilledwater"] = { label = "Distilledwater" },
    ["dosidos_leaf"] = { label = "Dosidos Leaf" },
    ["dosidos_seed"] = { label = "Dosidos Graine" },
    ["dosidos_trimmed_bud"] = { label = "Dosidos Trimmed Bud" },
    ["dosidos_untrimmed_bud"] = { label = "Dosidos Untrimmed Bud" },
    ["drug_lean"] = { label = "Drogue Lean" },
    ["drug_phone"] = { label = "Drogue Phone" },
    ["ecgonine"] = { label = "Ecgonine" },
    ["emptychembottles"] = { label = "Emptychembottles" },
    ["formaldehyde"] = { label = "Formaldehyde" },
    ["gelpills_blue"] = { label = "Gelpills Blue" },
    ["gelpills_pink"] = { label = "Gelpills Pink" },
    ["gelpills_red"] = { label = "Gelpills Rouge" },
    ["gelpills_yellow"] = { label = "Gelpills Yellow" },
    ["greengelato_trimmed_bud"] = { label = "Greengelato Trimmed Bud" },
    ["hiqualitysoil"] = { label = "Hiqualitysoil" },
    ["hiqualnutrients"] = { label = "Hiqualnutrients" },
    ["joint"] = { label = "Joint" },
    ["joint2"] = { label = "Joint2" },
    ["lab"] = { label = "Lab" },
    ["lean"] = { label = "Lean" },
    ["lemonskunk_leaf"] = { label = "Lemonskunk Leaf" },
    ["lemonskunk_seed"] = { label = "Lemonskunk Graine" },
    ["lemonskunk_trimmed_bud"] = { label = "Lemonskunk Trimmed Bud" },
    ["lemonskunk_untrimmed_bud"] = { label = "Lemonskunk Untrimmed Bud" },
    ["liquid_sulfur"] = { label = "Liquid Soufre" },
    ["lithium"] = { label = "Lithium" },
    ["lithiumbarrel"] = { label = "Lithiumbarrel" },
    ["lowqualitysoil"] = { label = "Lowqualitysoil" },
    ["lsd"] = { label = "LSD" },
    ["lsdtab"] = { label = "Lsdtab" },
    ["magic_mushroom"] = { label = "Magique Champignon" },
    ["medqualnutrients"] = { label = "Medqualnutrients" },
    ["meth"] = { label = "Méthamphétamine" },
    ["meth_tray"] = { label = "Méthamphétamine Tray" },
    ["meth_tray2"] = { label = "Méthamphétamine Tray2" },
    ["methalmine2"] = { label = "Methalmine2" },
    ["methylamine_barrel"] = { label = "Methylamine Barrel" },
    ["muriatic_acid"] = { label = "Muriatic Acide" },
    ["murioticacid"] = { label = "Murioticacid" },
    ["murioticacidbarrel"] = { label = "Murioticacidbarrel" },
    ["northernlights_leaf"] = { label = "Northernlights Leaf" },
    ["northernlights_seed"] = { label = "Northernlights Graine" },
    ["northernlights_trimmed_bud"] = { label = "Northernlights Trimmed Bud" },
    ["northernlights_untrimmed_bud"] = { label = "Northernlights Untrimmed Bud" },
    ["ogkush_leaf"] = { label = "Ogkush Leaf" },
    ["ogkush_seed"] = { label = "Ogkush Graine" },
    ["ogkush_trimmed_bud"] = { label = "Ogkush Trimmed Bud" },
    ["ogkush_untrimmed_bud"] = { label = "Ogkush Untrimmed Bud" },
    ["peyote_button"] = { label = "Peyote Button" },
    ["peyote_seed"] = { label = "Peyote Graine" },
    ["pills_extasy"] = { label = "Pilules Extasy" },
    ["pills_fentanyl"] = { label = "Pilules Fentanyl" },
    ["plantpot"] = { label = "Plantpot" },
    ["plasticbag"] = { label = "Plasticbag" },
    ["poppy"] = { label = "Pavot" },
    ["rainbowbelts_leaf"] = { label = "Rainbowbelts Leaf" },
    ["rainbowbelts_seed"] = { label = "Rainbowbelts Graine" },
    ["rainbowbelts_trimmed_bud"] = { label = "Rainbowbelts Trimmed Bud" },
    ["rainbowbelts_untrimmed_bud"] = { label = "Rainbowbelts Untrimmed Bud" },
    ["red_sulfur"] = { label = "Rouge Soufre" },
    ["redsulfurbarrel"] = { label = "Redsulfurbarrel" },
    ["sacid"] = { label = "Sacid" },
    ["small-scale"] = { label = "Small Scale" },
    ["sodium_hydroxide"] = { label = "Sodium Hydroxide" },
    ["sodiumbicarbonate"] = { label = "Sodiumbicarbonate" },
    ["sodiumhydroxide"] = { label = "Sodiumhydroxide" },
    ["sodiumhydroxidebarrel"] = { label = "Sodiumhydroxidebarrel" },
    ["weed_butter"] = { label = "Weed Butter" },
    ["weed_gummies"] = { label = "Weed Gummies" },
    ["weed_laced"] = { label = "Weed Laced" },
    ["weed_oil"] = { label = "Weed Oil" },
    ["weed_ream"] = { label = "Weed Ream" },
    ["weedscissors"] = { label = "Weedscissors" },

    -- [Electronics]
    ["battery_9v"] = { label = "Pile 9v" },
    ["battery_aaa"] = { label = "Pile Aaa" },
    ["battery_d2"] = { label = "Pile D2" },
    ["battery_package_9v"] = { label = "Pile Paquet 9v" },
    ["battery_package_aaa"] = { label = "Pile Paquet Aaa" },
    ["battery_package_d2"] = { label = "Pile Paquet D2" },
    ["cdplayer"] = { label = "Cdplayer" },
    ["e2_cpu"] = { label = "E2 Cpu" },
    ["internals"] = { label = "Internals" },
    ["miniradio"] = { label = "Miniradio" },
    ["nikon"] = { label = "Nikon" },
    ["portablecopier"] = { label = "Portablecopier" },
    ["powerbank"] = { label = "Batterie externe" },
    ["printer_document"] = { label = "Imprimante Document" },
    ["quantum_cpu"] = { label = "Quantum Cpu" },
    ["radio"] = { label = "Radio" },
    ["radioscanner"] = { label = "Radioscanner" },
    ["server_drive"] = { label = "Serveur Clé" },
    ["simcard"] = { label = "Simcard" },
    ["standard_cpu"] = { label = "Standard Cpu" },
    ["stolencomputer"] = { label = "Stolencomputer" },
    ["tablet"] = { label = "Comprimé" },
    ["usb_drive1"] = { label = "USB Drive1" },
    ["usb_drive2"] = { label = "USB Drive2" },
    ["usb_drive3"] = { label = "USB Drive3" },
    ["usb_drive4"] = { label = "USB Drive4" },

    -- [Ems]
    ["Inhailer"] = { label = "Inhailer" },
    ["Trilenol"] = { label = "Trilenol" },
    ["aed"] = { label = "Aed" },
    ["antibiotics"] = { label = "Antibiotiques" },
    ["armbrace"] = { label = "Armbrace" },
    ["armor_ems"] = { label = "Armure Ems" },
    ["aspirin"] = { label = "Aspirin" },
    ["azithromycin"] = { label = "Azithromycin" },
    ["bandage"] = { label = "Bandage" },
    ["bloodbag"] = { label = "Bloodbag" },
    ["bloodsample"] = { label = "Bloodsample" },
    ["bodybrace"] = { label = "Bodybrace" },
    ["burndressing"] = { label = "Burndressing" },
    ["coldnflubox"] = { label = "Coldnflubox" },
    ["crutch"] = { label = "Béquille" },
    ["dramamine"] = { label = "Dramamine" },
    ["ephedrine"] = { label = "Ephedrine" },
    ["epi_pen"] = { label = "Epi Pen" },
    ["firstaid"] = { label = "Trousse de secours" },
    ["glucosemeter"] = { label = "Glucosemeter" },
    ["ifaks"] = { label = "Ifaks" },
    ["laxative"] = { label = "Laxative" },
    ["legbrace"] = { label = "Legbrace" },
    ["medbag2"] = { label = "Medbag2" },
    ["medbag3"] = { label = "Medbag3" },
    ["medbag4"] = { label = "Medbag4" },
    ["medbox"] = { label = "Boîte médicale" },
    ["medbox6"] = { label = "Medbox6" },
    ["mri"] = { label = "IRM" },
    ["neckbrace"] = { label = "Neckbrace" },
    ["oxy"] = { label = "Oxy" },
    ["oxygen"] = { label = "Oxygène" },
    ["painkillers"] = { label = "Antidouleur" },
    ["peptobismol"] = { label = "Peptobismol" },
    ["pseudophederine"] = { label = "Pseudophederine" },
    ["salinebag"] = { label = "Salinebag" },
    ["surgicalkit"] = { label = "Surgicalkit" },
    ["suturekit"] = { label = "Suturekit" },
    ["syringe"] = { label = "Seringue" },
    ["syringefull"] = { label = "Syringefull" },
    ["walkstick"] = { label = "Walkstick" },
    ["walkstick2"] = { label = "Walkstick2" },
    ["xray"] = { label = "Radiographie" },

    -- [Farming]
    ["apple"] = { label = "Apple" },
    ["apple_crate"] = { label = "Apple Caisse" },
    ["barley"] = { label = "Barley" },
    ["barley_sack"] = { label = "Barley Sac" },
    ["barley_seed"] = { label = "Barley Graine" },
    ["blueberry"] = { label = "Blueberry" },
    ["blueberry_crate"] = { label = "Blueberry Caisse" },
    ["blueberry_seed"] = { label = "Blueberry Graine" },
    ["broccoli"] = { label = "Broccoli" },
    ["broccoli_crate"] = { label = "Broccoli Caisse" },
    ["broccoli_seed"] = { label = "Broccoli Graine" },
    ["cactus_seed"] = { label = "Cactus Graine" },
    ["cactusfruit"] = { label = "Cactusfruit" },
    ["cactusfruit_crate"] = { label = "Cactusfruit Caisse" },
    ["carrot"] = { label = "Carrot" },
    ["carrot_crate"] = { label = "Carrot Caisse" },
    ["carrot_raw"] = { label = "Carrot Cru" },
    ["carrot_seed"] = { label = "Carrot Graine" },
    ["corn"] = { label = "Corn" },
    ["corn_crate"] = { label = "Corn Caisse" },
    ["corn_raw"] = { label = "Corn Cru" },
    ["corn_seed"] = { label = "Corn Graine" },
    ["cucumber"] = { label = "Cucumber" },
    ["cucumber_crate"] = { label = "Cucumber Caisse" },
    ["cucumber_seed"] = { label = "Cucumber Graine" },
    ["egg"] = { label = "Egg" },
    ["egg_crate"] = { label = "Egg Caisse" },
    ["emptycrate"] = { label = "Emptycrate" },
    ["emptysack"] = { label = "Emptysack" },
    ["farm_fertilizer"] = { label = "Farm Engrais" },
    ["farmguide"] = { label = "Farmguide" },
    ["garden_pitcher"] = { label = "Jardin Arrosoir" },
    ["garden_shovel"] = { label = "Jardin Pelle" },
    ["lemon"] = { label = "Lemon" },
    ["lemon_crate"] = { label = "Lemon Caisse" },
    ["lettuce"] = { label = "Lettuce" },
    ["lettuce_crate"] = { label = "Lettuce Caisse" },
    ["lettuce_seed"] = { label = "Lettuce Graine" },
    ["lime"] = { label = "Lime" },
    ["lime_crate"] = { label = "Lime Caisse" },
    ["maize"] = { label = "Maize" },
    ["maize_sack"] = { label = "Maize Sac" },
    ["maize_seed"] = { label = "Maize Graine" },
    ["milk"] = { label = "Lait" },
    ["milk_crate"] = { label = "Lait Caisse" },
    ["milk_pail"] = { label = "Lait Seau" },
    ["milking_pail"] = { label = "Milking Seau" },
    ["mushroom"] = { label = "Champignon" },
    ["mushroom_sack"] = { label = "Champignon Sac" },
    ["mushroom_seed"] = { label = "Champignon Graine" },
    ["orange"] = { label = "Orange" },
    ["orange_crate"] = { label = "Orange Caisse" },
    ["peach"] = { label = "Peach" },
    ["peach_crate"] = { label = "Peach Caisse" },
    ["pineapple"] = { label = "Pineapple" },
    ["pineapple_crate"] = { label = "Pineapple Caisse" },
    ["pineapple_seed"] = { label = "Pineapple Graine" },
    ["potato"] = { label = "Potato" },
    ["potato_raw"] = { label = "Potato Cru" },
    ["potato_sack"] = { label = "Potato Sac" },
    ["potato_seed"] = { label = "Potato Graine" },
    ["strawberry"] = { label = "Strawberry" },
    ["strawberry_crate"] = { label = "Strawberry Caisse" },
    ["strawberry_seed"] = { label = "Strawberry Graine" },
    ["tomato"] = { label = "Tomato" },
    ["tomato_crate"] = { label = "Tomato Caisse" },
    ["tomato_seed"] = { label = "Tomato Graine" },
    ["watering_can"] = { label = "Arrosage Canette" },
    ["watering_can_full"] = { label = "Arrosage Canette Plein" },
    ["wheat"] = { label = "Wheat" },
    ["wheat_bag"] = { label = "Wheat Sac" },
    ["wheat_seed"] = { label = "Wheat Graine" },

    -- [Fishing]
    ["antipatharia_coral"] = { label = "Antipatharia Coral" },
    ["atum"] = { label = "Thon" },
    ["baleia"] = { label = "Baleine" },
    ["dendrogyra_coral"] = { label = "Dendrogyra Coral" },
    ["fishbait"] = { label = "Fishbait" },
    ["fishbaitillegal"] = { label = "Fishbaitillegal" },
    ["fishicebox"] = { label = "Fishicebox" },
    ["fishing_net1"] = { label = "Fishing Net1" },
    ["fishing_rod1"] = { label = "Fishing Rod1" },
    ["fishing_rod2"] = { label = "Fishing Rod2" },
    ["fishing_rod3"] = { label = "Fishing Rod3" },
    ["fishing_rod4"] = { label = "Fishing Rod4" },
    ["fishtacklebox"] = { label = "Fishtacklebox" },
    ["golfinho"] = { label = "Dauphin" },
    ["o_anchovy"] = { label = "Anchovy" },
    ["o_codfish"] = { label = "Codfish" },
    ["o_giant_seabass"] = { label = "Giant Seabass" },
    ["o_grouper"] = { label = "Grouper" },
    ["o_kingcrab"] = { label = "Kingcrab" },
    ["o_lobster"] = { label = "Homard" },
    ["o_mackerel"] = { label = "Mackerel" },
    ["o_mahi_mahi"] = { label = "Mahi Mahi" },
    ["o_pacific_halibut"] = { label = "Pacific Halibut" },
    ["o_pacific_sardine"] = { label = "Pacific Sardine" },
    ["o_rainbow_trout"] = { label = "Rainbow Trout" },
    ["o_red_snapper"] = { label = "Rouge Snapper" },
    ["o_redfish"] = { label = "Redfish" },
    ["o_spot_prawn"] = { label = "Spot Prawn" },
    ["o_stingray"] = { label = "Stingray" },
    ["o_white_seabass"] = { label = "Blanc Seabass" },
    ["o_yellowfin_tuna"] = { label = "Yellowfin Thon" },
    ["peixegato"] = { label = "Silure" },
    ["r_black_crappie"] = { label = "Black Crappie" },
    ["r_bluegill"] = { label = "Bluegill" },
    ["r_brown_trout"] = { label = "Brown Trout" },
    ["r_catfish"] = { label = "Catfish" },
    ["r_chinook_salmon"] = { label = "Chinook Saumon" },
    ["r_coho_salmon"] = { label = "Coho Saumon" },
    ["r_common_carp"] = { label = "Common Carp" },
    ["r_cutthroat_trout"] = { label = "Cutthroat Trout" },
    ["r_largemouth_bass"] = { label = "Largemouth Bass" },
    ["r_perch"] = { label = "Perch" },
    ["r_striped_bass"] = { label = "Striped Bass" },
    ["r_talapia"] = { label = "Talapia" },
    ["r_white_sturgeon"] = { label = "Blanc Sturgeon" },

    -- [Food]
    ["alla"] = { label = "Alla" },
    ["americancheese"] = { label = "Americancheese" },
    ["bacalhaucozido"] = { label = "Bacalhaucozido" },
    ["bacon"] = { label = "Bacon" },
    ["baconburger"] = { label = "Baconburger" },
    ["baconcheesemelt"] = { label = "Baconcheesemelt" },
    ["baconegg"] = { label = "Baconegg" },
    ["baconroll"] = { label = "Baconroll" },
    ["banana"] = { label = "Banana" },
    ["bangers"] = { label = "Bangers" },
    ["baquette"] = { label = "Baquette" },
    ["base2"] = { label = "Base2" },
    ["basil"] = { label = "Basil" },
    ["beef_jerky"] = { label = "Beef Jerky" },
    ["bento"] = { label = "Bento" },
    ["bento2"] = { label = "Bento2" },
    ["bento3"] = { label = "Bento3" },
    ["bento4"] = { label = "Bento4" },
    ["bento5"] = { label = "Bento5" },
    ["bento6"] = { label = "Bento6" },
    ["boba"] = { label = "Boba" },
    ["bolognese"] = { label = "Bolognese" },
    ["box_chocolate"] = { label = "Boîte Chocolat" },
    ["box_meat"] = { label = "Boîte Viande" },
    ["box_seafood"] = { label = "Boîte Seafood" },
    ["bplate"] = { label = "Bplate" },
    ["breadslice"] = { label = "Breadslice" },
    ["bs_bun"] = { label = "Bs Bun" },
    ["bs_patty_raw"] = { label = "Bs Patty Cru" },
    ["burger-bleeder"] = { label = "Burger Bleeder" },
    ["burger-chickenmelt"] = { label = "Burger Chickenmelt" },
    ["burger-chickenwrap"] = { label = "Burger Chickenwrap" },
    ["burger-creampie"] = { label = "Burger Creampie" },
    ["burger-frozennugget"] = { label = "Burger Frozennugget" },
    ["burger-goatwrap"] = { label = "Burger Goatwrap" },
    ["burger-heartstopper"] = { label = "Burger Heartstopper" },
    ["burger-icecream-empty"] = { label = "Burger Icecream Vide" },
    ["burger-icecream"] = { label = "Burger Icecream" },
    ["burger-icecream2"] = { label = "Burger Icecream2" },
    ["burger-meatfree"] = { label = "Burger Meatfree" },
    ["burger-milk"] = { label = "Burger Lait" },
    ["burger-milkshake"] = { label = "Burger Milkshake" },
    ["burger-moneyshot"] = { label = "Burger Moneyshot" },
    ["burger-onion"] = { label = "Burger Onion" },
    ["burger-rimjob"] = { label = "Burger Rimjob" },
    ["burger-slicedonion"] = { label = "Burger Slicedonion" },
    ["burger-slicedpotato"] = { label = "Burger Slicedpotato" },
    ["burger-torpedo"] = { label = "Burger Torpedo" },
    ["burger"] = { label = "Burger" },
    ["burgerbun"] = { label = "Burgerbun" },
    ["burgermeat"] = { label = "Burgermeat" },
    ["burgerpatty"] = { label = "Burgerpatty" },
    ["burrito"] = { label = "Burrito" },
    ["cake1"] = { label = "Cake1" },
    ["cake2"] = { label = "Cake2" },
    ["cake3"] = { label = "Cake3" },
    ["cake4"] = { label = "Cake4" },
    ["cake_birthday1"] = { label = "Gâteau Birthday1" },
    ["cake_birthday2"] = { label = "Gâteau Birthday2" },
    ["cake_carrot"] = { label = "Gâteau Carrot" },
    ["cake_chocolate"] = { label = "Gâteau Chocolat" },
    ["cake_pineapple"] = { label = "Gâteau Pineapple" },
    ["cake_redvelvet"] = { label = "Gâteau Redvelvet" },
    ["cake_slice1"] = { label = "Gâteau Slice1" },
    ["cake_slice2"] = { label = "Gâteau Slice2" },
    ["cake_slice3"] = { label = "Gâteau Slice3" },
    ["cake_slice4"] = { label = "Gâteau Slice4" },
    ["cake_strawberry"] = { label = "Gâteau Strawberry" },
    ["cake_wedding1"] = { label = "Gâteau Wedding1" },
    ["cake_wedding2"] = { label = "Gâteau Wedding2" },
    ["cake_wedding3"] = { label = "Gâteau Wedding3" },
    ["cake_wedding4"] = { label = "Gâteau Wedding4" },
    ["cake_wedding5"] = { label = "Gâteau Wedding5" },
    ["cakepop"] = { label = "Cakepop" },
    ["cakepop2"] = { label = "Cakepop2" },
    ["cakepop3"] = { label = "Cakepop3" },
    ["cakepop4"] = { label = "Cakepop4" },
    ["candied_bacon"] = { label = "Candied Bacon" },
    ["candy1"] = { label = "Candy1" },
    ["candy2"] = { label = "Candy2" },
    ["candy_cane"] = { label = "Candy Cane" },
    ["candy_gummies"] = { label = "Candy Gummies" },
    ["candy_hard"] = { label = "Candy Hard" },
    ["candy_suckerb"] = { label = "Candy Suckerb" },
    ["candy_suckerg"] = { label = "Candy Suckerg" },
    ["candy_suckero"] = { label = "Candy Suckero" },
    ["candy_suckerp"] = { label = "Candy Suckerp" },
    ["candy_suckerr"] = { label = "Candy Suckerr" },
    ["cataccino"] = { label = "Cataccino" },
    ["catcookie"] = { label = "Catcookie" },
    ["catdonut"] = { label = "Catdonut" },
    ["catlatte"] = { label = "Catlatte" },
    ["catpizza"] = { label = "Catpizza" },
    ["catrice"] = { label = "Catrice" },
    ["cavalacozida"] = { label = "Cavalacozida" },
    ["cheddar"] = { label = "Cheddar" },
    ["cheeseburger"] = { label = "Cheeseburger" },
    ["cheesecake"] = { label = "Cheesecake" },
    ["chickenbreast"] = { label = "Chickenbreast" },
    ["chickenburger"] = { label = "Chickenburger" },
    ["chickenfaj"] = { label = "Chickenfaj" },
    ["chickenpie"] = { label = "Chickenpie" },
    ["chickensalad"] = { label = "Chickensalad" },
    ["chickensandwich"] = { label = "Chickensandwich" },
    ["chickenthighs"] = { label = "Chickenthighs" },
    ["chickenthing"] = { label = "Chickenthing" },
    ["chickhornstars"] = { label = "Chickhornstars" },
    ["chillimince"] = { label = "Chillimince" },
    ["chocolate1"] = { label = "Chocolate1" },
    ["chocolate10"] = { label = "Chocolate10" },
    ["chocolate2"] = { label = "Chocolate2" },
    ["chocolate3"] = { label = "Chocolate3" },
    ["chocolate4"] = { label = "Chocolate4" },
    ["chocolate5"] = { label = "Chocolate5" },
    ["chocolate6"] = { label = "Chocolate6" },
    ["chocolate7"] = { label = "Chocolate7" },
    ["chocolate8"] = { label = "Chocolate8" },
    ["chocolate9"] = { label = "Chocolate9" },
    ["chocpudding"] = { label = "Chocpudding" },
    ["churros"] = { label = "Churros" },
    ["coffee_generic"] = { label = "Coffee Generic" },
    ["coffee_generic2"] = { label = "Coffee Generic2" },
    ["coffee_generic3"] = { label = "Coffee Generic3" },
    ["coldweiner"] = { label = "Coldweiner" },
    ["cone_blueberry"] = { label = "Cone Blueberry" },
    ["cone_chocolate2"] = { label = "Cone Chocolate2" },
    ["cone_pistachio"] = { label = "Cone Pistachio" },
    ["cone_strawberry"] = { label = "Cone Strawberry" },
    ["cone_vanilla"] = { label = "Cone Vanilla" },
    ["cookie"] = { label = "Cookie" },
    ["cooking_chocolate"] = { label = "Cooking Chocolat" },
    ["cubasil"] = { label = "Cubasil" },
    ["cucumber"] = { label = "Cucumber" },
    ["cupcake_blue"] = { label = "Cupcake Blue" },
    ["cupcake_cherry"] = { label = "Cupcake Cherry" },
    ["cupcake_chocolate"] = { label = "Cupcake Chocolat" },
    ["cupcake_confetti"] = { label = "Cupcake Confetti" },
    ["cupcake_creamcheese"] = { label = "Cupcake Creamcheese" },
    ["cupcake_pistachio"] = { label = "Cupcake Pistachio" },
    ["cupcake_rainbow"] = { label = "Cupcake Rainbow" },
    ["cupcake_vanilla"] = { label = "Cupcake Vanilla" },
    ["dbl_hornburger"] = { label = "Dbl Hornburger" },
    ["dimsum1"] = { label = "Dimsum1" },
    ["dimsum2"] = { label = "Dimsum2" },
    ["dimsum3"] = { label = "Dimsum3" },
    ["dimsum4"] = { label = "Dimsum4" },
    ["dimsum5"] = { label = "Dimsum5" },
    ["dimsum6"] = { label = "Dimsum6" },
    ["donut1"] = { label = "Donut1" },
    ["donut10"] = { label = "Donut10" },
    ["donut11"] = { label = "Donut11" },
    ["donut2"] = { label = "Donut2" },
    ["donut3"] = { label = "Donut3" },
    ["donut4"] = { label = "Donut4" },
    ["donut5"] = { label = "Donut5" },
    ["donut6"] = { label = "Donut6" },
    ["donut7"] = { label = "Donut7" },
    ["donut8"] = { label = "Donut8" },
    ["donut9"] = { label = "Donut9" },
    ["durum1"] = { label = "Durum1" },
    ["durum2"] = { label = "Durum2" },
    ["durum3"] = { label = "Durum3" },
    ["durum4"] = { label = "Durum4" },
    ["durum5"] = { label = "Durum5" },
    ["durum6"] = { label = "Durum6" },
    ["durum7"] = { label = "Durum7" },
    ["eggbene"] = { label = "Eggbene" },
    ["eggs"] = { label = "Eggs" },
    ["emptymilkbottle"] = { label = "Emptymilkbottle" },
    ["enchi"] = { label = "Enchi" },
    ["enchilada"] = { label = "Enchilada" },
    ["fakecrab"] = { label = "Fakecrab" },
    ["farming_butter"] = { label = "Farming Butter" },
    ["farming_chickenbreast"] = { label = "Farming Chickenbreast" },
    ["farming_tomato"] = { label = "Farming Tomato" },
    ["fish_fillet"] = { label = "Poisson Fillet" },
    ["flour"] = { label = "Flour" },
    ["frenchfries_generic"] = { label = "Frenchfries Generic" },
    ["frenchtoast"] = { label = "Frenchtoast" },
    ["frenchtoast2"] = { label = "Frenchtoast2" },
    ["friedpick"] = { label = "Friedpick" },
    ["fries_gravy_cheese"] = { label = "Fries Gravy Fromage" },
    ["fruit_smoothie"] = { label = "Fruit Smoothie" },
    ["fruittart"] = { label = "Fruittart" },
    ["fruittart2"] = { label = "Fruittart2" },
    ["gelato"] = { label = "Gelato" },
    ["gp_salad"] = { label = "Gp Salad" },
    ["gp_soup_salad_sandwich_combo"] = { label = "Gp Soupe Salad Sandwich Combo" },
    ["gp_strawberry_shortcake"] = { label = "Gp Strawberry Shortcake" },
    ["grape"] = { label = "Grape" },
    ["grilled_wrap"] = { label = "Grilled Wrap" },
    ["ham"] = { label = "Ham" },
    ["hamburger"] = { label = "Hamburger" },
    ["hashbrown"] = { label = "Hashbrown" },
    ["hornburger"] = { label = "Hornburger" },
    ["hornsandwich"] = { label = "Hornsandwich" },
    ["hotdog_chili"] = { label = "Hotdog Chili" },
    ["hotdog_chillicheesedog"] = { label = "Hotdog Chillicheesedog" },
    ["hotdog_deluxe"] = { label = "Hotdog Deluxe" },
    ["hotdog_ketchup"] = { label = "Hotdog Ketchup" },
    ["hotdog_mustard"] = { label = "Hotdog Mustard" },
    ["hotdog_plain"] = { label = "Hotdog Plain" },
    ["hotdog_taco"] = { label = "Hotdog Taco" },
    ["hotdog_veggie"] = { label = "Hotdog Veggie" },
    ["hotdogbun"] = { label = "Hotdogbun" },
    ["hotdogmeat"] = { label = "Hotdogmeat" },
    ["ice_bag"] = { label = "Ice Sac" },
    ["ice_cup"] = { label = "Ice Cup" },
    ["instantcoffee"] = { label = "Instantcoffee" },
    ["jello"] = { label = "Jello" },
    ["juice_apple"] = { label = "Juice Apple" },
    ["juice_cranberry"] = { label = "Juice Cranberry" },
    ["juice_grape"] = { label = "Juice Grape" },
    ["juice_pineapple"] = { label = "Juice Pineapple" },
    ["kebab1"] = { label = "Kebab1" },
    ["kebab2"] = { label = "Kebab2" },
    ["kebab3"] = { label = "Kebab3" },
    ["kebab4"] = { label = "Kebab4" },
    ["lemonade"] = { label = "Lemonade" },
    ["loaded_burger"] = { label = "Loaded Burger" },
    ["maccheese"] = { label = "Maccheese" },
    ["matcha"] = { label = "Matcha" },
    ["meatball"] = { label = "Meatball" },
    ["medfruits"] = { label = "Medfruits" },
    ["mint"] = { label = "Mint" },
    ["miso"] = { label = "Miso" },
    ["mochameow"] = { label = "Mochameow" },
    ["mochiblue"] = { label = "Mochiblue" },
    ["mochigreen"] = { label = "Mochigreen" },
    ["mochiorange"] = { label = "Mochiorange" },
    ["mochipink"] = { label = "Mochipink" },
    ["mozz"] = { label = "Mozz" },
    ["nacho_plate"] = { label = "Nacho Plate" },
    ["nachos"] = { label = "Nachos" },
    ["noodlebowl"] = { label = "Noodlebowl" },
    ["noodles"] = { label = "Noodles" },
    ["nori"] = { label = "Nori" },
    ["olives"] = { label = "Olives" },
    ["pasta"] = { label = "Pasta" },
    ["pawcakes"] = { label = "Pawcakes" },
    ["pear"] = { label = "Pear" },
    ["pickle"] = { label = "Pickle" },
    ["pickleburger"] = { label = "Pickleburger" },
    ["piecrust"] = { label = "Piecrust" },
    ["pizza_cannabisvegetariana"] = { label = "Pizza Cannabisvegetariana" },
    ["pizza_capricciosa"] = { label = "Pizza Capricciosa" },
    ["pizza_diavola"] = { label = "Pizza Diavola" },
    ["pizza_margherita"] = { label = "Pizza Margherita" },
    ["pizza_marinara"] = { label = "Pizza Marinara" },
    ["pizza_proscuttio"] = { label = "Pizza Proscuttio" },
    ["pizza_vegetariana"] = { label = "Pizza Vegetariana" },
    ["pizzadough"] = { label = "Pizzadough" },
    ["potato_chips"] = { label = "Potato Chips" },
    ["pulledpork_sliders"] = { label = "Pulledpork Sliders" },
    ["pulledporksand"] = { label = "Pulledporksand" },
    ["purrito"] = { label = "Purrito" },
    ["ramen"] = { label = "Ramen" },
    ["ranchwrap"] = { label = "Ranchwrap" },
    ["rawbacon"] = { label = "Rawbacon" },
    ["rawhotdog"] = { label = "Rawhotdog" },
    ["rawsausage"] = { label = "Rawsausage" },
    ["ribs"] = { label = "Ribs" },
    ["rice"] = { label = "Riz" },
    ["rottenapple"] = { label = "Rottenapple" },
    ["sake"] = { label = "Sake" },
    ["salami"] = { label = "Salami" },
    ["sandwich_bacon"] = { label = "Sandwich Bacon" },
    ["sandwich_blt"] = { label = "Sandwich Blt" },
    ["sandwich_eggsalad"] = { label = "Sandwich Eggsalad" },
    ["sandwich_grilledcheese"] = { label = "Sandwich Grilledcheese" },
    ["sandwich_grilledcheese2"] = { label = "Sandwich Grilledcheese2" },
    ["sandwich_ham"] = { label = "Sandwich Ham" },
    ["sandwich_hamcheese"] = { label = "Sandwich Hamcheese" },
    ["sandwich_moldy"] = { label = "Sandwich Moldy" },
    ["sandwich_ruben"] = { label = "Sandwich Ruben" },
    ["sandwich_sub"] = { label = "Sandwich Sub" },
    ["sandwich_tuna"] = { label = "Sandwich Thon" },
    ["sausage"] = { label = "Sausage" },
    ["sausageeggs"] = { label = "Sausageeggs" },
    ["seafood_beerbatterfish"] = { label = "Seafood Beerbatterfish" },
    ["seafood_calamari"] = { label = "Seafood Calamari" },
    ["seafood_calamari2"] = { label = "Seafood Calamari2" },
    ["seafood_crabcakes"] = { label = "Seafood Crabcakes" },
    ["seafood_grilledfish"] = { label = "Seafood Grilledfish" },
    ["seafood_grilledsalmon"] = { label = "Seafood Grilledsalmon" },
    ["seafood_kingcrab"] = { label = "Seafood Kingcrab" },
    ["seafood_lobster"] = { label = "Seafood Homard" },
    ["seafood_lobster2"] = { label = "Seafood Lobster2" },
    ["seafood_paella"] = { label = "Seafood Paella" },
    ["seafood_pescatore"] = { label = "Seafood Pescatore" },
    ["seafood_salmon"] = { label = "Seafood Saumon" },
    ["seafood_sardines"] = { label = "Seafood Sardines" },
    ["seafood_seabass"] = { label = "Seafood Seabass" },
    ["seafood_shrimpcocktail"] = { label = "Seafood Shrimpcocktail" },
    ["seafood_shrimppasta"] = { label = "Seafood Shrimppasta" },
    ["shreddedpork"] = { label = "Shreddedpork" },
    ["slicedapple"] = { label = "Slicedapple" },
    ["slicedtomato"] = { label = "Slicedtomato" },
    ["slider"] = { label = "Slider" },
    ["soda_fruit_punch"] = { label = "Soda Fruit Punch" },
    ["soda_lime"] = { label = "Soda Lime" },
    ["soda_mandarin"] = { label = "Soda Mandarin" },
    ["soda_pineapple"] = { label = "Soda Pineapple" },
    ["soda_strawberry"] = { label = "Soda Strawberry" },
    ["sodasyrup"] = { label = "Sodasyrup" },
    ["soup_bean"] = { label = "Soupe Bean" },
    ["soup_broccoli"] = { label = "Soupe Broccoli" },
    ["soup_chickennoodle"] = { label = "Soupe Chickennoodle" },
    ["soup_chickenveg"] = { label = "Soupe Chickenveg" },
    ["soup_chickenveg2"] = { label = "Soupe Chickenveg2" },
    ["soup_clamchowder2"] = { label = "Soupe Clamchowder2" },
    ["soup_cornchowder"] = { label = "Soupe Cornchowder" },
    ["soup_creamypotato"] = { label = "Soupe Creamypotato" },
    ["soup_frenchonion"] = { label = "Soupe Frenchonion" },
    ["soup_frenchonion2"] = { label = "Soupe Frenchonion2" },
    ["soup_gazpacho"] = { label = "Soupe Gazpacho" },
    ["soup_miso"] = { label = "Soupe Miso" },
    ["soup_mushroom"] = { label = "Soupe Champignon" },
    ["soup_seafood"] = { label = "Soupe Seafood" },
    ["soup_squash"] = { label = "Soupe Squash" },
    ["soup_tomato"] = { label = "Soupe Tomato" },
    ["soup_tomato2"] = { label = "Soupe Tomato2" },
    ["soup_vegetable"] = { label = "Soupe Vegetable" },
    ["splate"] = { label = "Splate" },
    ["squid"] = { label = "Squid" },
    ["steakburger"] = { label = "Steakburger" },
    ["strawberryfloat"] = { label = "Strawberryfloat" },
    ["stuffedpotato"] = { label = "Stuffedpotato" },
    ["sugar"] = { label = "Sugar" },
    ["sunday_caramel"] = { label = "Sunday Caramel" },
    ["sunday_chocolate"] = { label = "Sunday Chocolat" },
    ["sunday_strawberry"] = { label = "Sunday Strawberry" },
    ["surimi"] = { label = "Surimi" },
    ["sushi1"] = { label = "Sushi1" },
    ["sushi10"] = { label = "Sushi10" },
    ["sushi11"] = { label = "Sushi11" },
    ["sushi2"] = { label = "Sushi2" },
    ["sushi3"] = { label = "Sushi3" },
    ["sushi4"] = { label = "Sushi4" },
    ["sushi5"] = { label = "Sushi5" },
    ["sushi6"] = { label = "Sushi6" },
    ["sushi7"] = { label = "Sushi7" },
    ["sushi8"] = { label = "Sushi8" },
    ["sushi9"] = { label = "Sushi9" },
    ["taco_beef"] = { label = "Taco Beef" },
    ["taco_chicken"] = { label = "Taco Poulet" },
    ["taco_chicken2"] = { label = "Taco Chicken2" },
    ["taco_fish"] = { label = "Taco Poisson" },
    ["taco_plate"] = { label = "Taco Plate" },
    ["taco_shell"] = { label = "Taco Shell" },
    ["tea_black"] = { label = "Tea Black" },
    ["tea_bubble"] = { label = "Tea Bubble" },
    ["tea_bubble_blue"] = { label = "Tea Bubble Blue" },
    ["tea_bubble_green"] = { label = "Tea Bubble Green" },
    ["tea_bubble_orange"] = { label = "Tea Bubble Orange" },
    ["tea_bubble_pink"] = { label = "Tea Bubble Pink" },
    ["tea_green"] = { label = "Tea Green" },
    ["tea_green_matcha"] = { label = "Tea Green Matcha" },
    ["tea_iced"] = { label = "Tea Iced" },
    ["tea_peach_ided"] = { label = "Tea Peach Ided" },
    ["teabag"] = { label = "Teabag" },
    ["tf_tostada"] = { label = "Tf Tostada" },
    ["tiramisu"] = { label = "Tiramisu" },
    ["tofu"] = { label = "Tofu" },
    ["tostada"] = { label = "Tostada" },
    ["tostada_shell"] = { label = "Tostada Shell" },
    ["tots"] = { label = "Tots" },
    ["tripleburger"] = { label = "Tripleburger" },
    ["uwu-cafe-box"] = { label = "Uwu Cafe Boîte" },
    ["uwu_bubbletea"] = { label = "Uwu Bubbletea" },
    ["veggiewrap"] = { label = "Veggiewrap" },
    ["water_bottle"] = { label = "Eau Bottle" },
    ["water_bottle2"] = { label = "Eau Bottle2" },
    ["water_bulk"] = { label = "Eau Bulk" },
    ["whip_cream"] = { label = "Whip Cream" },
    ["wings"] = { label = "Wings" },
    ["wrap"] = { label = "Wrap" },

    -- [Garage]
    ["accesstool"] = { label = "Accesstool" },
    ["advancedkit"] = { label = "Advancedkit" },
    ["anchor"] = { label = "Anchor" },
    ["anglegrinder"] = { label = "Anglegrinder" },
    ["armour"] = { label = "Armour" },
    ["beltcutter"] = { label = "Beltcutter" },
    ["bprooftires"] = { label = "Bprooftires" },
    ["brakes1"] = { label = "Brakes1" },
    ["brakes2"] = { label = "Brakes2" },
    ["brakes3"] = { label = "Brakes3" },
    ["bumper"] = { label = "Bumper" },
    ["carjack"] = { label = "Carjack" },
    ["carstereo"] = { label = "Carstereo" },
    ["cleaningkit"] = { label = "Cleaningkit" },
    ["cutter"] = { label = "Cutter" },
    ["drifttires"] = { label = "Drifttires" },
    ["exhaust"] = { label = "Exhaust" },
    ["harness"] = { label = "Harness" },
    ["headlights"] = { label = "Headlights" },
    ["hood"] = { label = "Hood" },
    ["horn"] = { label = "Horn" },
    ["livery"] = { label = "Livery" },
    ["mechanic_tools"] = { label = "Mechanic Tools" },
    ["mechboard"] = { label = "Mechboard" },
    ["mirror"] = { label = "Mirror" },
    ["nitrogen"] = { label = "Nitrogen" },
    ["nitrous"] = { label = "Nitrous" },
    ["pwasher"] = { label = "Pwasher" },
    ["repairkit"] = { label = "Repairkit" },
    ["rifle_drummag"] = { label = "Fusil Drummag" },
    ["rim"] = { label = "Rim" },
    ["rims"] = { label = "Rims" },
    ["rollcage"] = { label = "Rollcage" },
    ["roof"] = { label = "Roof" },
    ["seat"] = { label = "Seat" },
    ["shonen"] = { label = "Shonen" },
    ["skirts"] = { label = "Skirts" },
    ["spanner"] = { label = "Spanner" },
    ["spoiler"] = { label = "Spoiler" },
    ["spray"] = { label = "Spray" },
    ["spray_remover"] = { label = "Spray Remover" },
    ["suspension1"] = { label = "Suspension1" },
    ["suspension2"] = { label = "Suspension2" },
    ["suspension3"] = { label = "Suspension3" },
    ["suspension4"] = { label = "Suspension4" },
    ["tint_supplies"] = { label = "Tint Supplies" },
    ["tires"] = { label = "Tires" },
    ["toolbox"] = { label = "Toolbox" },
    ["transmission1"] = { label = "Transmission1" },
    ["transmission2"] = { label = "Transmission2" },
    ["transmission3"] = { label = "Transmission3" },
    ["tunerchip"] = { label = "Tunerchip" },
    ["turbo"] = { label = "Turbo" },
    ["tyre_bennys"] = { label = "Tyre Bennys" },
    ["tyre_bespoke"] = { label = "Tyre Bespoke" },
    ["tyre_f1"] = { label = "Tyre F1" },
    ["tyre_highend"] = { label = "Tyre Highend" },
    ["tyre_lowrider"] = { label = "Tyre Lowrider" },
    ["tyre_motorcycle"] = { label = "Tyre Motorcycle" },
    ["tyre_muscle"] = { label = "Tyre Muscle" },
    ["tyre_offroad"] = { label = "Tyre Offroad" },
    ["tyre_sport"] = { label = "Tyre Sport" },
    ["tyre_street"] = { label = "Tyre Street" },
    ["tyre_suv"] = { label = "Tyre Suv" },
    ["tyre_tuner"] = { label = "Tyre Tuner" },
    ["underglow_controller"] = { label = "Underglow Controller" },
    ["v10engine"] = { label = "V10engine" },
    ["v12engine"] = { label = "V12engine" },
    ["v8engine"] = { label = "V8engine" },

    -- [Hunting]
    ["boar_tusks"] = { label = "Boar Tusks" },
    ["cougar_claw"] = { label = "Cougar Claw" },
    ["cowpelt"] = { label = "Cowpelt" },
    ["coyote_teeth"] = { label = "Coyote Teeth" },
    ["coyotepelt"] = { label = "Coyotepelt" },
    ["deer_horns"] = { label = "Deer Horns" },
    ["hunting_ammo"] = { label = "Hunting Ammo" },
    ["hunting_rifle"] = { label = "Hunting Fusil" },
    ["huntingbait"] = { label = "Huntingbait" },
    ["meat"] = { label = "Viande" },
    ["meat_boar"] = { label = "Viande Boar" },
    ["meat_chicken"] = { label = "Viande Poulet" },
    ["meat_chickenhawk"] = { label = "Viande Chickenhawk" },
    ["meat_cormorant"] = { label = "Viande Cormorant" },
    ["meat_cougar"] = { label = "Viande Cougar" },
    ["meat_cow"] = { label = "Viande Cow" },
    ["meat_coyote"] = { label = "Viande Coyote" },
    ["meat_deer"] = { label = "Viande Deer" },
    ["meat_dolphin"] = { label = "Viande Dolphin" },
    ["meat_mtlion"] = { label = "Viande Mtlion" },
    ["meat_pig"] = { label = "Viande Pig" },
    ["meat_rabbit"] = { label = "Viande Rabbit" },
    ["meat_rat"] = { label = "Viande Rat" },
    ["meat_shark"] = { label = "Viande Shark" },
    ["meat_stingray"] = { label = "Viande Stingray" },
    ["meat_whale"] = { label = "Viande Whale" },
    ["pigpelt"] = { label = "Pigpelt" },
    ["rabbit_foot"] = { label = "Rabbit Foot" },
    ["rabbitfur"] = { label = "Rabbitfur" },
    ["skin_boar"] = { label = "Skin Boar" },
    ["skin_cougar"] = { label = "Skin Cougar" },
    ["skin_deer"] = { label = "Skin Deer" },
    ["skin_dolphin"] = { label = "Skin Dolphin" },
    ["skin_mtlion"] = { label = "Skin Mtlion" },
    ["skin_pig"] = { label = "Skin Pig" },
    ["skin_rabbit"] = { label = "Skin Rabbit" },
    ["skin_rat"] = { label = "Skin Rat" },
    ["skin_sasquatch"] = { label = "Skin Sasquatch" },
    ["skin_shark"] = { label = "Skin Shark" },
    ["skin_stingray"] = { label = "Skin Stingray" },
    ["skin_whale"] = { label = "Skin Whale" },

    -- [Jewelry]
    ["10kgoldchain"] = { label = "10kgoldchain" },
    ["diamond_earring"] = { label = "Diamond Earring" },
    ["diamond_earring_silver"] = { label = "Diamond Earring Silver" },
    ["diamond_necklace"] = { label = "Diamond Necklace" },
    ["diamond_necklace_silver"] = { label = "Diamond Necklace Silver" },
    ["diamond_ring"] = { label = "Diamond Ring" },
    ["diamond_ring_silver"] = { label = "Diamond Ring Silver" },
    ["emerald_earring"] = { label = "Emerald Earring" },
    ["emerald_earring_silver"] = { label = "Emerald Earring Silver" },
    ["emerald_necklace"] = { label = "Emerald Necklace" },
    ["emerald_necklace_silver"] = { label = "Emerald Necklace Silver" },
    ["emerald_ring"] = { label = "Emerald Ring" },
    ["emerald_ring_silver"] = { label = "Emerald Ring Silver" },
    ["gold_earring"] = { label = "Gold Earring" },
    ["gold_ring"] = { label = "Gold Ring" },
    ["goldchain"] = { label = "Goldchain" },
    ["goldchain2"] = { label = "Goldchain2" },
    ["ruby_earring"] = { label = "Ruby Earring" },
    ["ruby_earring_silver"] = { label = "Ruby Earring Silver" },
    ["ruby_necklace"] = { label = "Ruby Necklace" },
    ["ruby_necklace_silver"] = { label = "Ruby Necklace Silver" },
    ["ruby_ring"] = { label = "Ruby Ring" },
    ["ruby_ring_silver"] = { label = "Ruby Ring Silver" },
    ["sapphire_earring"] = { label = "Sapphire Earring" },
    ["sapphire_earring_silver"] = { label = "Sapphire Earring Silver" },
    ["sapphire_necklace"] = { label = "Sapphire Necklace" },
    ["sapphire_necklace_silver"] = { label = "Sapphire Necklace Silver" },
    ["sapphire_ring"] = { label = "Sapphire Ring" },
    ["sapphire_ring_silver"] = { label = "Sapphire Ring Silver" },
    ["silver_earring"] = { label = "Silver Earring" },
    ["silver_ring"] = { label = "Silver Ring" },
    ["silverchain"] = { label = "Silverchain" },

    -- [Licenses And Ids]
    ["certificate"] = { label = "Certificate" },
    ["id_card"] = { label = "Id Card" },
    ["lawyerpass"] = { label = "Lawyerpass" },
    ["licence_weapon"] = { label = "Licence Weapon" },
    ["license_driver"] = { label = "License Driver" },
    ["license_fishing"] = { label = "License Fishing" },
    ["license_hunting"] = { label = "License Hunting" },
    ["license_marijuana_grow"] = { label = "License Marijuana Grow" },
    ["license_marijuana_use"] = { label = "License Marijuana Use" },
    ["lisence_pilot"] = { label = "Lisence Pilot" },
    ["title"] = { label = "Title" },

    -- [Mining]
    ["Steel ingot"] = { label = "Steel ingot" },
    ["carbon"] = { label = "Carbon" },
    ["copperore"] = { label = "Copperore" },
    ["diamond"] = { label = "Diamond" },
    ["emerald"] = { label = "Emerald" },
    ["goldingot"] = { label = "Goldingot" },
    ["goldore"] = { label = "Goldore" },
    ["goldpan"] = { label = "Goldpan" },
    ["ironingot"] = { label = "Ironingot" },
    ["ironore"] = { label = "Ironore" },
    ["miningdrill"] = { label = "Miningdrill" },
    ["mininglaser"] = { label = "Mininglaser" },
    ["pickaxe"] = { label = "Pickaxe" },
    ["ruby"] = { label = "Ruby" },
    ["sapphire"] = { label = "Sapphire" },
    ["silveringot"] = { label = "Silveringot" },
    ["silverore"] = { label = "Silverore" },
    ["stone"] = { label = "Stone" },
    ["uncut_diamond"] = { label = "Uncut Diamond" },
    ["uncut_emerald"] = { label = "Uncut Emerald" },
    ["uncut_ruby"] = { label = "Uncut Ruby" },
    ["uncut_sapphire"] = { label = "Uncut Sapphire" },

    -- [Misc]
    ["aceofhearts"] = { label = "Aceofhearts" },
    ["backpack4"] = { label = "Backpack4" },
    ["backpack5"] = { label = "Backpack5" },
    ["blueprint"] = { label = "Blueprint" },
    ["bmx"] = { label = "Bmx" },
    ["box_empty"] = { label = "Boîte Vide" },
    ["carkeys"] = { label = "Carkeys" },
    ["carkeys2"] = { label = "Carkeys2" },
    ["casino_chips_100"] = { label = "Casino Chips 100" },
    ["casino_chips_50"] = { label = "Casino Chips 50" },
    ["casino_chips_500"] = { label = "Casino Chips 500" },
    ["casino_chips_blu"] = { label = "Casino Chips Blu" },
    ["casino_chips_red"] = { label = "Casino Chips Rouge" },
    ["casino_chips_yel"] = { label = "Casino Chips Yel" },
    ["cigar"] = { label = "Cigare" },
    ["cigar_estancia"] = { label = "Cigare Estancia" },
    ["cigarette"] = { label = "Cigarette" },
    ["cigarette2"] = { label = "Cigarette2" },
    ["diving_gear"] = { label = "Diving Gear" },
    ["jerry_can"] = { label = "Jerry Canette" },
    ["key1"] = { label = "Key1" },
    ["key2"] = { label = "Key2" },
    ["key3"] = { label = "Key3" },
    ["lighter"] = { label = "Lighter" },
    ["lighter2"] = { label = "Lighter2" },
    ["lottery_ticket"] = { label = "Lottery Ticket" },
    ["newspaper"] = { label = "Newspaper" },
    ["parachute"] = { label = "Parachute" },
    ["printed_image"] = { label = "Printed Image" },
    ["reciept1"] = { label = "Reciept1" },
    ["reciept2"] = { label = "Reciept2" },
    ["scratch_ticket"] = { label = "Scratch Ticket" },
    ["scratch_ticket2"] = { label = "Scratch Ticket2" },
    ["skateboard"] = { label = "Skateboard" },
    ["stickynote"] = { label = "Stickynote" },
    ["umbrella"] = { label = "Umbrella" },
    ["vehiclecoupon"] = { label = "Vehiclecoupon" },
    ["wood"] = { label = "Wood" },

    -- [Moonshine]
    ["empty_growler"] = { label = "Vide Growler" },
    ["empty_growler2"] = { label = "Vide Growler2" },
    ["emtpy_growler2"] = { label = "Emtpy Growler2" },
    ["moonshine"] = { label = "Moonshine" },
    ["moonshine_distill"] = { label = "Moonshine Distill" },
    ["moonshine_ferm"] = { label = "Moonshine Ferm" },
    ["moonshine_mash"] = { label = "Moonshine Mash" },
    ["vodka_bootleg"] = { label = "Vodka Bootleg" },
    ["vodka_distill"] = { label = "Vodka Distill" },
    ["vodka_ferm"] = { label = "Vodka Ferm" },
    ["vodka_mash"] = { label = "Vodka Mash" },
    ["yeast"] = { label = "Yeast" },

    -- [Pd]
    ["armor"] = { label = "Armure" },
    ["breathalyzer"] = { label = "Breathalyzer" },
    ["dnatestkit"] = { label = "Dnatestkit" },
    ["document"] = { label = "Document" },
    ["drone"] = { label = "Drone" },
    ["drugtestkit"] = { label = "Drugtestkit" },
    ["emptydocuments"] = { label = "Emptydocuments" },
    ["evidence"] = { label = "Evidence" },
    ["fingerprintreader"] = { label = "Fingerprintreader" },
    ["gopro"] = { label = "Gopro" },
    ["goprotablet"] = { label = "Goprotablet" },
    ["gsrtestkit"] = { label = "Gsrtestkit" },
    ["handcuffs"] = { label = "Handcuffs" },
    ["megaphone"] = { label = "Megaphone" },
    ["police_stormram"] = { label = "Police Stormram" },
    ["ticket"] = { label = "Ticket" },
    ["ticketbook"] = { label = "Ticketbook" },

    -- [Tools]
    ["shovel"] = { label = "Pelle" },

    -- [Vapes]
    ["vape1"] = { label = "Vape1" },
    ["vape2"] = { label = "Vape2" },
    ["vape3"] = { label = "Vape3" },
    ["vape4"] = { label = "Vape4" },
    ["vape5"] = { label = "Vape5" },
    ["vape_juice_apple"] = { label = "Vape Juice Apple" },
    ["vape_juice_mango"] = { label = "Vape Juice Mango" },
    ["vape_juice_menthol"] = { label = "Vape Juice Menthol" },
    ["vape_juice_strawberry"] = { label = "Vape Juice Strawberry" },
    ["vape_juice_tobacco"] = { label = "Vape Juice Tobacco" },
    ["vape_juice_watermelon"] = { label = "Vape Juice Watermelon" },

    -- [Weapons]
    ["binoculars"] = { label = "Jumelles" },
    ["mg_ammo"] = { label = "Mg Ammo" },
    ["nvg"] = { label = "Nvg" },
    ["pistol_ammo"] = { label = "Pistol Ammo" },
    ["pistol_extendedclip"] = { label = "Pistol Extendedclip" },
    ["pistol_suppressor"] = { label = "Pistol Suppressor" },
    ["rifle_ammo"] = { label = "Fusil Ammo" },
    ["shotgun_ammo"] = { label = "Shotgun Ammo" },
    ["smg_ammo"] = { label = "Smg Ammo" },
    ["smg_flashlight"] = { label = "Smg Flashlight" },
    ["smg_scope"] = { label = "Smg Scope" },
    ["thermal_katana_orange"] = { label = "Thermal Katana Orange" },
    ["weapon_briefcase"] = { label = "Weapon Briefcase" },
    ["weapon_briefcase2"] = { label = "Weapon Briefcase2" },
    ["weapon_flashlight"] = { label = "Weapon Flashlight" },
    ["weapon_garbagebag"] = { label = "Weapon Garbagebag" },
    ["weapon_goodnightbat"] = { label = "Weapon Goodnightbat" },
    ["weapon_hammer"] = { label = "Weapon Hammer" },
    ["weapon_handcuffs"] = { label = "Weapon Handcuffs" },
    ["weapon_knuckle"] = { label = "Weapon Knuckle" },
    ["weapon_lovehate"] = { label = "Weapon Lovehate" },
    ["weapon_nightstick"] = { label = "Weapon Nightstick" },
    ["weaponthreading"] = { label = "Weaponthreading" },
    ["weapontint_army"] = { label = "Weapontint Army" },
    ["weapontint_black"] = { label = "Weapontint Black" },
    ["weapontint_gold"] = { label = "Weapontint Gold" },
    ["weapontint_green"] = { label = "Weapontint Green" },
    ["weapontint_lspd"] = { label = "Weapontint Lspd" },
    ["weapontint_orange"] = { label = "Weapontint Orange" },
    ["weapontint_pink"] = { label = "Weapontint Pink" },
    ["weapontint_plat"] = { label = "Weapontint Plat" },
    ["zipties"] = { label = "Zipties" },
    ["zipties2"] = { label = "Zipties2" },

}
