-- Farming seeds
    ["barley_seed"] = { label = "Graine d'orge" },
    ["blueberry_seed"] = { label = "Graine de myrtille" },
    ["broccoli_seed"] = { label = "Graine de brocoli" },
    ["cactus_seed"] = { label = "Graine de cactus" },
    ["carrot_seed"] = { label = "Graine de carotte" },
    ["corn_seed"] = { label = "Graine de maïs" },
    ["cucumber_seed"] = { label = "Graine de concombre" },
    ["lettuce_seed"] = { label = "Graine de laitue" },
    ["maize_seed"] = { label = "Graine de maïs" },
    ["mushroom_seed"] = { label = "Graine de champignon" },
    ["pineapple_seed"] = { label = "Graine d'ananas" },
    ["potato_seed"] = { label = "Graine de pomme de terre" },
    ["strawberry_seed"] = { label = "Graine de fraise" },
    ["tomato_seed"] = { label = "Graine de tomate" },
    ["wheat_seed"] = { label = "Graine de blé" },
-- Farming produce
    ["apple"] = { label = "Pomme" },
    ["barley"] = { label = "Orge" },
    ["blueberry"] = { label = "Myrtille" },
    ["broccoli"] = { label = "Brocoli" },
    ["cactusfruit"] = { label = "Fruit de cactus" },
    ["carrot"] = { label = "Carotte" },
    ["corn"] = { label = "Maïs" },
    ["cucumber"] = { label = "Concombre" },
    ["egg"] = { label = "Oeuf" },
    ["lemon"] = { label = "Citron" },
    ["lettuce"] = { label = "Laitue" },
    ["lime"] = { label = "Citron vert" },
    ["maize"] = { label = "Maïs" },
    ["milk"] = { label = "Lait" },
    ["mushroom"] = { label = "Champignon" },
    ["orange"] = { label = "Orange" },
    ["peach"] = { label = "Pêche" },
    ["pineapple"] = { label = "Ananas" },
    ["potato"] = { label = "Pomme de terre" },
    ["strawberry"] = { label = "Fraise" },
    ["tomato"] = { label = "Tomate" },
    ["wheat"] = { label = "Blé" },
-- Farming raw
    ["carrot_raw"] = { label = "Carotte crue" },
    ["corn_raw"] = { label = "Maïs cru" },
    ["potato_raw"] = { label = "Pomme de terre crue" },
-- Farming crates
    ["apple_crate"] = { label = "Caisse de pommes" },
    ["blueberry_crate"] = { label = "Caisse de myrtilles" },
    ["broccoli_crate"] = { label = "Caisse de brocolis" },
    ["carrot_crate"] = { label = "Caisse de carottes" },
    ["corn_crate"] = { label = "Caisse de maïs" },
    ["cucumber_crate"] = { label = "Caisse de concombres" },
    ["egg_crate"] = { label = "Caisse d'œufs" },
    ["lemon_crate"] = { label = "Caisse de citrons" },
    ["lettuce_crate"] = { label = "Caisse de laitues" },
    ["lime_crate"] = { label = "Caisse de citrons verts" },
    ["milk_crate"] = { label = "Caisse de lait" },
    ["peach_crate"] = { label = "Caisse de pêches" },
    ["pineapple_crate"] = { label = "Caisse d'ananas" },
    ["strawberry_crate"] = { label = "Caisse de fraises" },
    ["tomato_crate"] = { label = "Caisse de tomates" },
-- Farming sacks
    ["barley_sack"] = { label = "Sac d'orge" },
    ["maize_sack"] = { label = "Sac de maïs" },
    ["mushroom_sack"] = { label = "Sac de champignons" },
    ["potato_sack"] = { label = "Sac de pommes de terre" },
    ["wheat_bag"] = { label = "Sac de blé" },
-- Farming tools
    ["farmguide"] = { label = "Guide agricole" },
    ["farm_fertilizer"] = { label = "Engrais" },
    ["garden_pitcher"] = { label = "Arrosoir de jardin" },
    ["garden_shovel"] = { label = "Pelle de jardin" },
    ["milking_pail"] = { label = "Seau de traite" },
    ["milk_pail"] = { label = "Seau à lait" },
    ["watering_can"] = { label = "Arrosoir" },
    ["watering_can_full"] = { label = "Arrosoir plein" },
-- Farming other
    ["emptycrate"] = { label = "Caisse vide" },
    ["emptysack"] = { label = "Sac vide" },

